using System.Threading.Tasks;
using Content.Shared._CE.Procedural;
using Content.Shared.Destructible.Thresholds;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Server._CE.Procedural.Generators.Procedural.GenerationSteps;

/// <summary>
/// Generates a web of connected rooms of the given type, starting from a grid coordinate.
/// New rooms are appended to randomly selected rooms from the growing frontier.
/// </summary>
[DataDefinition]
public sealed partial class GenerateRoomWeb : CEDungeonGenerationStep
{
    /// <summary>
    /// Grid coordinate where the first room will be placed.
    /// </summary>
    [DataField]
    public Vector2i Source;

    /// <summary>
    /// Room type assigned to every room generated by this step.
    /// </summary>
    [DataField(required: true)]
    public ProtoId<CERoomTypePrototype> RoomType;

    /// <summary>
    /// Number of rooms to generate (picked randomly in range, inclusive).
    /// </summary>
    [DataField]
    public MinMax Count = new(8, 10);

    /// <inheritdoc/>
    public override async Task Execute(CEGenerationStepContext context)
    {
        var comp = context.Comp;
        var gridStep = context.MaxRoomSize + 1;
        var roomSize = new Vector2i(context.MaxRoomSize, context.MaxRoomSize);
        var targetCount = context.Random.Next(Count.Min, Count.Max + 1);

        if (targetCount <= 0)
            return;

        // Build occupied set from rooms already placed by previous steps.
        var occupied = new HashSet<Vector2i>(comp.Rooms.Count + targetCount);
        foreach (var existing in comp.Rooms)
        {
            occupied.Add(existing.GridCoord);
        }

        // Frontier: room indices (into comp.Rooms) that have at least one free cardinal neighbour.
        var frontier = new List<int>();

        // If the source cell is already occupied, seed the frontier with the room there.
        // Otherwise place the first room at source.
        if (occupied.Contains(Source))
        {
            foreach (var existing in comp.Rooms)
            {
                if (existing.GridCoord == Source && CEGenerationStepContext.HasEmptyNeighbor(existing.GridCoord, occupied))
                {
                    frontier.Add(existing.Index);
                    break;
                }
            }
        }
        else
        {
            var firstRoom = new CEProceduralAbstractRoom
            {
                Index = comp.Rooms.Count,
                GridCoord = Source,
                Position = new Vector2i(Source.X * gridStep, Source.Y * gridStep),
                Size = roomSize,
                RoomType = RoomType,
            };
            comp.Rooms.Add(firstRoom);
            occupied.Add(Source);
            frontier.Add(firstRoom.Index);
            targetCount--;
        }

        var yieldCounter = 0;

        while (targetCount > 0 && frontier.Count > 0)
        {
            if (++yieldCounter % 50 == 0)
                await context.Suspend();

            var frontierIdx = context.Random.Next(frontier.Count);
            var parentRoomIdx = frontier[frontierIdx];
            var parent = comp.Rooms[parentRoomIdx];

            // Collect free cardinal neighbours.
            var freeDirections = new List<Vector2i>();
            foreach (var dir in CEGenerationStepContext.Directions)
            {
                if (!occupied.Contains(parent.GridCoord + dir))
                    freeDirections.Add(dir);
            }

            if (freeDirections.Count == 0)
            {
                // Parent is fully surrounded; remove from frontier.
                frontier[frontierIdx] = frontier[^1];
                frontier.RemoveAt(frontier.Count - 1);
                continue;
            }

            var chosenDir = context.Random.Pick(freeDirections);
            var newGridCoord = parent.GridCoord + chosenDir;

            var newRoom = new CEProceduralAbstractRoom
            {
                Index = comp.Rooms.Count,
                GridCoord = newGridCoord,
                Position = new Vector2i(newGridCoord.X * gridStep, newGridCoord.Y * gridStep),
                Size = roomSize,
                RoomType = RoomType,
            };
            comp.Rooms.Add(newRoom);
            occupied.Add(newGridCoord);

            comp.Connections.Add(new CEProceduralRoomConnection
            {
                RoomA = parentRoomIdx,
                RoomB = newRoom.Index,
            });

            if (CEGenerationStepContext.HasEmptyNeighbor(newGridCoord, occupied))
                frontier.Add(newRoom.Index);

            if (!CEGenerationStepContext.HasEmptyNeighbor(parent.GridCoord, occupied))
            {
                frontier[frontierIdx] = frontier[^1];
                frontier.RemoveAt(frontier.Count - 1);
            }

            // Evict any previously-frontier neighbours that are now surrounded.
            foreach (var dir in CEGenerationStepContext.Directions)
            {
                var neighborCoord = newGridCoord + dir;
                if (neighborCoord == parent.GridCoord)
                    continue;

                if (!occupied.Contains(neighborCoord))
                    continue;

                if (CEGenerationStepContext.HasEmptyNeighbor(neighborCoord, occupied))
                    continue;

                for (var fi = frontier.Count - 1; fi >= 0; fi--)
                {
                    if (comp.Rooms[frontier[fi]].GridCoord == neighborCoord)
                    {
                        frontier[fi] = frontier[^1];
                        frontier.RemoveAt(frontier.Count - 1);
                        break;
                    }
                }
            }

            targetCount--;
        }
    }
}
