- type: entity
  id: CEMobDamageable
  save: false
  abstract: true
  components:
  - type: CEDamageable
  - type: CEDestructible
    destroyThreshold: 20
    destroySound:
      collection: gib
  - type: Pullable
  - type: CEFlammable
    stackDelta: -1

- type: entity
  id: CEMobMagical
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: CEMagicEnergyContainer

- type: entity
  id: CEMobCombat
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: CombatMode
  - type: StatusIcon #TODO not here!
