using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    public const string StyleClassChatContainer = "ChatContainer";
    public const string StyleClassChatOutput = "ChatOutput";

    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
        // Minimap: top-left, just below the system buttons (TopBar) row.
        SetAnchorAndMarginPreset(Minimap, LayoutPreset.TopLeft, margin: 10);
        UpdateMinimapPosition();
        TopBar.OnResized += UpdateMinimapPosition;

        // CrystallEdge - mana and health spheres
        var gap = 310f;
        var manaOffset = ManaBar.MinSize.X / 2f + gap;
        var healthOffset = -(HealthBar.MinSize.X + manaOffset);

        SetAnchorAndMarginPreset(HealthBar, LayoutPreset.CenterBottom);
        SetMarginLeft(HealthBar, healthOffset);

        SetAnchorAndMarginPreset(ManaBar, LayoutPreset.CenterBottom);
        SetMarginLeft(ManaBar, manaOffset);

        // Soul indicator: small horizontal block placed to the right of the mana sphere.
        var soulGap = 20f;
        var soulOffset = manaOffset + ManaBar.MinSize.X / 2f + soulGap + SoulBar.MinSize.X / 2f;
        SetAnchorAndMarginPreset(SoulBar, LayoutPreset.CenterBottom);
        SetMarginLeft(SoulBar, soulOffset);

        // Currency bar: slightly right of SoulBar left edge, above it but half its own height lower.
        SetAnchorAndMarginPreset(CurrencyBar, LayoutPreset.CenterBottom, margin: (int)(SoulBar.MinSize.Y + 4 - CurrencyBar.MinSize.Y / 2f));
        SetMarginLeft(CurrencyBar, soulOffset + 4);
        SetMarginRight(CurrencyBar, soulOffset + 4 + 400f);

        // Stamina bar at center bottom
        SetAnchorAndMarginPreset(StaminaBar, LayoutPreset.CenterBottom, margin: 80);
        SetMarginLeft(StaminaBar, -StaminaBar.MinSize.X / 2f);
        SetMarginRight(StaminaBar, StaminaBar.MinSize.X / 2f);

        // Actions bar: always horizontal, placed above the stamina/hotbar area.
        SetAnchorPreset(Actions, LayoutPreset.BottomWide);
        SetMarginLeft(Actions, 0);
        SetMarginRight(Actions, 0);

        // Boss health bar: top center, below the menu bar row.
        SetAnchorAndMarginPreset(BossHealthBar, LayoutPreset.CenterTop, margin: 80);
        SetMarginLeft(BossHealthBar, -BossHealthBar.MinSize.X / 2f);
        SetMarginRight(BossHealthBar, BossHealthBar.MinSize.X / 2f);
        // CrystallEdge end

        ScreenContainer.OnSplitResizeFinished += () =>
            OnChatResized?.Invoke(new Vector2(ScreenContainer.SplitFraction, 0));

        ViewportContainer.OnResized += ResizeActionContainer;
        Hotbar.OnResized += ResizeActionContainer;

        ResizeActionContainer();
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        var maxWidth = ViewportContainer.Size.X - indent;
        if (maxWidth > 0)
            Actions.ActionsContainer.MaxGridWidth = maxWidth;

        var staminaTop = 80f + StaminaBar.MinSize.Y;
        var hotbarTop = 5f + Hotbar.Size.Y;
        var actionHeight = MathF.Max(Actions.MinSize.Y, 64f);
        var actionBottomOffset = MathF.Max(staminaTop, hotbarTop) + 8f - actionHeight / 2f;
        SetMarginBottom(Actions, -actionBottomOffset);
        SetMarginTop(Actions, -actionBottomOffset - actionHeight);
    }

    private void UpdateMinimapPosition()
    {
        // Position the minimap directly below the system buttons (TopBar) row.
        var topBarHeight = MathF.Max(TopBar.Size.Y, TopBar.MinSize.Y);
        var top = topBarHeight + 15f;
        SetMarginTop(Minimap, top);
        SetMarginBottom(Minimap, top + Minimap.MinSize.Y);
        SetMarginLeft(Minimap, 10f);
        SetMarginRight(Minimap, 10f + Minimap.MinSize.X);
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
    }
}
