using System.IO;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Editor.UI;

/// <summary>
/// Main content area that displays the raw YAML text of a selected prototype file.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditorViewControl : PanelContainer
{
    public EditorViewControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Reads and displays the YAML content for a file path.
    /// </summary>
    public void OpenFile(string filePath)
    {
        ContentLabel.Text = File.ReadAllText(filePath);
        PlaceholderLabel.Visible = false;
        ContentScroll.Visible = true;
    }

    /// <summary>
    /// Clears the editor view back to the placeholder state.
    /// </summary>
    public void Clear()
    {
        ContentLabel.Text = "";
        PlaceholderLabel.Visible = true;
        ContentScroll.Visible = false;
    }
}
