using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Editor.UI;

/// <summary>
/// Root control for the prototype editor. Contains the file tree, tab bar, and editor area.
/// Applies a Discord-inspired dark theme using StyleBoxFlat backgrounds.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditorMainControl : Control
{
    // Discord-inspired dark theme colors
    public static readonly Color BgPrimary = Color.FromHex("#313338");
    public static readonly Color BgSecondary = Color.FromHex("#2b2d31");
    public static readonly Color BgTertiary = Color.FromHex("#1e1f22");
    public static readonly Color BgSurface = Color.FromHex("#383a40");
    public static readonly Color BgSurfaceHover = Color.FromHex("#404249");
    public static readonly Color Border = Color.FromHex("#3f4147");
    public static readonly Color BorderSubtle = Color.FromHex("#35373c");
    public static readonly Color Accent = Color.FromHex("#5865f2");
    public static readonly Color AccentDim = Color.FromHex("#2a2d5e");
    public static readonly Color TextPrimary = Color.FromHex("#f2f3f5");
    public static readonly Color TextSecondary = Color.FromHex("#b5bac1");
    public static readonly Color TextMuted = Color.FromHex("#6d6f78");
    public static readonly Color ErrorColor = Color.FromHex("#da373c");
    public static readonly Color SuccessColor = Color.FromHex("#23a559");

    public EditorMainControl()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        // Apply themed backgrounds
        SidebarPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgTertiary,
            BorderColor = Border,
            BorderThickness = new Thickness(0, 0, 1, 0),
        };

        SidebarHeader.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgTertiary,
            BorderColor = Border,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        TabBarPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgTertiary,
            BorderColor = Border,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        EditorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgPrimary,
        };

        StatusBarPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgTertiary,
            BorderColor = Border,
            BorderThickness = new Thickness(0, 1, 0, 0),
        };
    }
}
