using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Editor.UI;

/// <summary>
/// Main content area that parses a YAML prototype file and renders
/// each prototype as a <see cref="PrototypeCardControl"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditorViewControl : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public EditorViewControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Parses the YAML file at the given path and renders prototype cards.
    /// </summary>
    public void OpenFile(string filePath)
    {
        CardsContainer.RemoveAllChildren();

        var prototypes = PrototypeDataParser.ParseFile(filePath, _proto);

        foreach (var proto in prototypes)
        {
            var card = new PrototypeCardControl();
            card.Populate(proto.Kind, proto.Id, proto.Parent, proto.IsAbstract, proto.Fields);
            CardsContainer.AddChild(card);
        }

        PlaceholderLabel.Visible = prototypes.Count == 0;
        ContentScroll.Visible = prototypes.Count > 0;
    }

    /// <summary>
    /// Clears the editor view back to the placeholder state.
    /// </summary>
    public void Clear()
    {
        CardsContainer.RemoveAllChildren();
        PlaceholderLabel.Visible = true;
        ContentScroll.Visible = false;
    }
}
