using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Editor.UI;

/// <summary>
/// Main content area that parses a YAML prototype file and renders
/// each prototype as a <see cref="PrototypeCardControl"/>.
/// Manages per-file edit sessions with undo/redo support.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditorViewControl : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    /// <summary>
    /// Per-file edit sessions keyed by absolute path.
    /// </summary>
    private readonly Dictionary<string, FileEditSession> _sessions = new();

    private string? _currentPath;

    /// <summary>
    /// Fired when dirty state changes for the current file. Args: (filePath, isDirty).
    /// </summary>
    public event Action<string, bool>? OnDirtyChanged;

    public EditorViewControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Gets the edit session for the currently open file, or null.
    /// </summary>
    public FileEditSession? CurrentSession =>
        _currentPath != null && _sessions.TryGetValue(_currentPath, out var s) ? s : null;

    /// <summary>
    /// Parses the YAML file at the given path and renders prototype cards.
    /// </summary>
    public void OpenFile(string filePath)
    {
        _currentPath = filePath;

        // Get or create a session
        if (!_sessions.TryGetValue(filePath, out var session))
        {
            session = new FileEditSession(filePath);
            session.OnDirtyChanged += dirty => OnDirtyChanged?.Invoke(filePath, dirty);
            _sessions[filePath] = session;
        }

        // Parse the file
        session.Prototypes = PrototypeDataParser.ParseFile(filePath, _proto);

        // Apply any pending edits/resets from the session
        ApplyPendingEdits(session);

        RebuildCards(session);
    }

    /// <summary>
    /// Clears the editor view back to the placeholder state.
    /// </summary>
    public void Clear()
    {
        _currentPath = null;
        CardsContainer.RemoveAllChildren();
        PlaceholderLabel.Visible = true;
        ContentScroll.Visible = false;
    }

    /// <summary>
    /// Performs undo on the current file. Returns true if an action was undone.
    /// </summary>
    public bool Undo()
    {
        var session = CurrentSession;
        if (session == null)
            return false;

        var edit = session.Undo();
        if (edit == null)
            return false;

        // Re-parse and rebuild to reflect the undo
        session.Prototypes = PrototypeDataParser.ParseFile(session.FilePath, _proto);
        ApplyPendingEdits(session);
        RebuildCards(session);
        return true;
    }

    /// <summary>
    /// Performs redo on the current file. Returns true if an action was redone.
    /// </summary>
    public bool Redo()
    {
        var session = CurrentSession;
        if (session == null)
            return false;

        var edit = session.Redo();
        if (edit == null)
            return false;

        session.Prototypes = PrototypeDataParser.ParseFile(session.FilePath, _proto);
        ApplyPendingEdits(session);
        RebuildCards(session);
        return true;
    }

    /// <summary>
    /// Marks the current session as saved (clears dirty/history).
    /// </summary>
    public void MarkSaved()
    {
        CurrentSession?.MarkSaved();
    }

    /// <summary>
    /// Gets the session for a given file path, if it exists.
    /// </summary>
    public FileEditSession? GetSession(string filePath)
    {
        return _sessions.GetValueOrDefault(filePath);
    }

    /// <summary>
    /// Removes session for the given file (e.g. when closing a tab).
    /// </summary>
    public void CloseSession(string filePath)
    {
        _sessions.Remove(filePath);
    }

    // ── Private ──

    private void ApplyPendingEdits(FileEditSession session)
    {
        foreach (var proto in session.Prototypes)
        {
            foreach (var field in proto.Fields)
            {
                var key = (proto.Id, field.Name);

                if (session.PendingResets.Contains(key))
                {
                    // Reset: show inherited value, mark as not overridden
                    field.Value = field.InheritedValue;
                    field.IsOverridden = false;
                }
                else if (session.PendingEdits.TryGetValue(key, out var editedValue))
                {
                    field.Value = editedValue;
                    field.IsOverridden = true;
                }
            }
        }
    }

    private void RebuildCards(FileEditSession session)
    {
        CardsContainer.RemoveAllChildren();

        foreach (var proto in session.Prototypes)
        {
            var card = new PrototypeCardControl();
            card.Populate(proto.Kind, proto.Id, proto.Parent, proto.IsAbstract, proto.Fields);

            card.OnFieldEdited += (protoId, fieldName, newValue) =>
                HandleFieldEdited(session, protoId, fieldName, newValue);

            card.OnFieldReset += (protoId, fieldName) =>
                HandleFieldReset(session, protoId, fieldName);

            CardsContainer.AddChild(card);
        }

        PlaceholderLabel.Visible = session.Prototypes.Count == 0;
        ContentScroll.Visible = session.Prototypes.Count > 0;
    }

    private void HandleFieldEdited(FileEditSession session, string protoId, string fieldName, string newValue)
    {
        // Find the current field data to get old value
        var field = FindField(session, protoId, fieldName);
        if (field == null)
            return;

        var oldValue = field.Value;
        var wasOverridden = field.IsOverridden;

        session.RecordEdit(protoId, fieldName, oldValue, newValue, wasOverridden);

        // Update in-memory state
        field.Value = newValue;
        field.IsOverridden = true;

        // Rebuild cards to reflect override visual state (bar, label style, reset button)
        RebuildCards(session);
    }

    private void HandleFieldReset(FileEditSession session, string protoId, string fieldName)
    {
        var field = FindField(session, protoId, fieldName);
        if (field == null)
            return;

        var oldValue = field.Value;
        var wasOverridden = field.IsOverridden;

        session.RecordReset(protoId, fieldName, oldValue, wasOverridden);

        // Re-parse and rebuild to show inherited values
        session.Prototypes = PrototypeDataParser.ParseFile(session.FilePath, _proto);
        ApplyPendingEdits(session);
        RebuildCards(session);
    }

    private static EditorFieldData? FindField(FileEditSession session, string protoId, string fieldName)
    {
        return session.Prototypes
            .Where(p => p.Id == protoId)
            .SelectMany(p => p.Fields)
            .FirstOrDefault(f => f.Name == fieldName);
    }
}
