using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Editor.UI;

/// <summary>
/// Renders a single prototype as a card with a header (kind + ID + parent)
/// and a list of data field rows showing field name and value.
/// Overridden fields are displayed with bold text and a colored left bar.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeCardControl : PanelContainer
{
    /// <summary>
    /// Color used for the override indicator bar on the left side of overridden fields.
    /// </summary>
    private static readonly Color OverrideBarColor = Color.FromHex("#4FC3F7");

    public PrototypeCardControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Populates the card with prototype data.
    /// </summary>
    /// <param name="kind">Prototype kind string (e.g. "entity").</param>
    /// <param name="id">Prototype ID.</param>
    /// <param name="parent">Comma-separated parent IDs, or null.</param>
    /// <param name="isAbstract">Whether this prototype is abstract.</param>
    /// <param name="fields">
    /// List of (fieldName, displayValue, isOverridden) tuples.
    /// </param>
    public void Populate(
        string kind,
        string id,
        string? parent,
        bool isAbstract,
        List<EditorFieldData> fields)
    {
        KindBadge.Text = $"[{kind}]";
        IdLabel.Text = id;
        ParentLabel.Text = parent != null ? $"← {parent}" : "";
        ParentLabel.Visible = parent != null;

        if (isAbstract)
            IdLabel.AddStyleClass(StyleClass.LabelWeak);

        FieldsContainer.RemoveAllChildren();

        foreach (var field in fields)
        {
            AddFieldRow(field);
        }
    }

    private void AddFieldRow(EditorFieldData field)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 0,
        };

        // Override indicator bar (thin colored strip on the left)
        var bar = new PanelContainer
        {
            MinWidth = 3,
            MaxWidth = 3,
            VerticalExpand = true,
            ModulateSelfOverride = field.IsOverridden ? OverrideBarColor : Color.Transparent,
        };
        row.AddChild(bar);

        // Field name label
        var nameLabel = new Label
        {
            Text = field.Name,
            MinWidth = 160,
            MaxWidth = 160,
            Margin = new Thickness(8, 2, 4, 2),
            ClipText = true,
        };
        nameLabel.AddStyleClass(StyleClass.LabelSubText);

        if (field.IsOverridden)
            nameLabel.AddStyleClass(StyleClass.Highlight);

        row.AddChild(nameLabel);

        // Value label displayed as monospace text
        var valueLabel = new Label
        {
            Text = field.Value,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2, 8, 2),
            ClipText = true,
        };
        valueLabel.AddStyleClass(StyleClass.Monospace);

        if (field.IsOverridden)
            valueLabel.AddStyleClass(StyleClass.Highlight);

        row.AddChild(valueLabel);

        FieldsContainer.AddChild(row);
    }
}

/// <summary>
/// Data for a single field row on a prototype card.
/// </summary>
public sealed class EditorFieldData
{
    /// <summary>
    /// YAML key / DataField tag name.
    /// </summary>
    public string Name { get; init; } = "";

    /// <summary>
    /// Display value as text.
    /// </summary>
    public string Value { get; init; } = "";

    /// <summary>
    /// Whether this field is locally overridden in the YAML file
    /// (as opposed to inherited or at C# default).
    /// </summary>
    public bool IsOverridden { get; init; }
}
