using System.Linq;
using Content.Editor.Prototype;
using Content.Editor.UI.FieldControls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Markdown;
using Robust.Shared.Serialization.Markdown.Mapping;
using Robust.Shared.Serialization.Markdown.Sequence;
using Robust.Shared.Serialization.Markdown.Value;

namespace Content.Editor.UI;

/// <summary>
/// A styled card representing a single prototype entry.
/// Shows ALL fields from the prototype type (local, inherited, default).
/// Supports override visualization, reset buttons, and generic component handling.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeCard : PanelContainer
{
    private readonly PrototypeEntry _entry;
    private readonly IPrototypeManager _prototypeManager;
    private readonly ISerializationManager _serializationManager;
    private readonly IComponentFactory? _componentFactory;
    private bool _isCollapsed;

    /// <summary>
    /// Per-field validation error messages. Updated by <see cref="SetFieldErrors"/>.
    /// Key is the field tag (e.g. "name", "desc"), value is the error message.
    /// </summary>
    private Dictionary<string, string> _fieldErrors = new();

    /// <summary>
    /// Fired when a field value is changed. Args: (fieldTag, newValue).
    /// </summary>
    public event Action<string, object?>? OnFieldChanged;

    /// <summary>
    /// Fired when a field is reset (removed from local mapping).
    /// </summary>
    public event Action<string>? OnFieldReset;

    /// <summary>
    /// Fired when the parent is changed.
    /// </summary>
    public event Action<string[]?>? OnParentChanged;

    /// <summary>
    /// Fired when the user requests deletion of this prototype.
    /// </summary>
    public event Action? OnDeleteRequested;

    public PrototypeCard(
        PrototypeEntry entry,
        IPrototypeManager prototypeManager,
        ISerializationManager serializationManager,
        IComponentFactory? componentFactory = null)
    {
        RobustXamlLoader.Load(this);

        _entry = entry;
        _prototypeManager = prototypeManager;
        _serializationManager = serializationManager;
        _componentFactory = componentFactory;

        ApplyCardStyling();

        // Set up header data
        TypeBadge.Text = entry.TypeString.ToUpperInvariant();
        IdEdit.Text = entry.Id ?? "";

        // Only show abstract toggle for IInheritingPrototype
        if (entry.PrototypeType != null && PrototypeReflector.SupportsInheritance(entry.PrototypeType))
        {
            AbstractToggle.Visible = true;
            AbstractToggle.Pressed = entry.IsAbstract;

            // Show parent editor
            ParentPanel.Visible = true;
            ParentEdit.Text = entry.Parents != null
                ? string.Join(", ", entry.Parents)
                : "";
        }

        // Wire up events
        IdEdit.OnTextEntered += OnIdChanged;
        AbstractToggle.OnToggled += OnAbstractToggled;
        CollapseButton.OnPressed += OnCollapsePressed;
        ApplyParentButton.OnPressed += OnApplyParent;
        ParentEdit.OnTextEntered += _ => ApplyParentChange();
        DeleteButton.OnPressed += _ => OnDeleteRequested?.Invoke();
        AddComponentButton.OnPressed += _ => OnAddComponentPressed();

        // Right-click context menu on header
        HeaderPanel.OnKeyBindDown += OnHeaderRightClick;

        // Populate fields
        PopulateAllFields();
    }

    private void ApplyCardStyling()
    {
        // Card outer container
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = EditorMainControl.BgSecondary,
            BorderColor = EditorMainControl.Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
        };

        // Header: accent tint for normal, gray for abstract
        var headerColor = _entry.IsAbstract
            ? Color.FromHex("#28292c")
            : Color.FromHex("#2d2f47");
        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = headerColor,
        };

        // Type badge: pill-style
        TypeBadgePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = _entry.IsAbstract
                ? Color.FromHex("#666666")
                : EditorMainControl.Accent,
        };

        // Parent bar: subtle blue tint
        ParentPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1d2230"),
            BorderColor = EditorMainControl.BorderSubtle,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        // Components section header: top border separator
        CompHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BorderColor = EditorMainControl.Border,
            BorderThickness = new Thickness(0, 2, 0, 0),
        };
    }

    /// <summary>
    /// Populates ALL fields from the prototype type, plus any extra YAML keys.
    /// Shows each field with its source (local/inherited/default).
    /// </summary>
    private void PopulateAllFields()
    {
        FieldsContainer.RemoveAllChildren();
        ComponentsList.RemoveAllChildren();
        ComponentsSection.Visible = false;

        if (_entry.PrototypeType == null)
        {
            // Unknown type — just show raw YAML fields
            PopulateRawFields();
            return;
        }

        // Resolve parent data for inheritance display
        var parentData = InheritanceResolver.ResolveParentData(_entry, _prototypeManager);

        // Get all metadata fields for this prototype type
        var metaFields = PrototypeReflector.GetFields(_entry.PrototypeType);
        var handledTags = new HashSet<string> { "type", "id", "parent", "abstract" };

        // Render metadata fields first (in declaration order)
        foreach (var meta in metaFields)
        {
            // Components handled separately
            if (meta.IsComponentRegistry)
            {
                ComponentsSection.Visible = true;
                PopulateComponents(parentData);
                handledTags.Add(meta.Tag);
                continue;
            }

            handledTags.Add(meta.Tag);

            var source = InheritanceResolver.GetFieldSource(meta.Tag, _entry.Mapping, parentData);
            var valueNode = InheritanceResolver.GetFieldValue(meta.Tag, _entry.Mapping, parentData);

            Action? onReset = null;
            if (source == FieldSource.Local)
            {
                var tag = meta.Tag;
                onReset = () => ResetField(tag);
            }

            var fieldRow = FieldControlFactory.CreateFieldRow(
                meta.Tag,
                valueNode,
                source,
                _serializationManager,
                newValue => OnFieldEdited(meta.Tag, newValue),
                onReset,
                errorMessage: _fieldErrors.GetValueOrDefault(meta.Tag),
                isRequired: meta.IsRequired,
                onOverride: newValue => OnFieldOverridden(meta.Tag, newValue));

            FieldsContainer.AddChild(fieldRow);
        }

        // Render any extra YAML keys not covered by metadata
        if (_entry.Mapping != null)
        {
            foreach (var (key, value) in _entry.Mapping)
            {
                if (handledTags.Contains(key))
                    continue;

                if (key == "components")
                    continue;

                var fieldRow = FieldControlFactory.CreateFieldRow(
                    key,
                    value,
                    FieldSource.Local,
                    _serializationManager,
                    newValue => OnFieldEdited(key, newValue),
                    () => ResetField(key));

                FieldsContainer.AddChild(fieldRow);
            }
        }

        // Show inherited-only fields that are in parent data but not in metadata
        if (parentData != null)
        {
            foreach (var (key, value) in parentData)
            {
                if (handledTags.Contains(key))
                    continue;

                if (key == "components")
                    continue;

                handledTags.Add(key);

                var source = InheritanceResolver.GetFieldSource(key, _entry.Mapping, parentData);
                var valueNode = InheritanceResolver.GetFieldValue(key, _entry.Mapping, parentData);

                var fieldRow = FieldControlFactory.CreateFieldRow(
                    key,
                    valueNode,
                    source,
                    _serializationManager,
                    newValue => OnFieldEdited(key, newValue));

                FieldsContainer.AddChild(fieldRow);
            }
        }
    }

    private void PopulateRawFields()
    {
        if (_entry.Mapping == null)
            return;

        var skipKeys = new HashSet<string> { "type", "id", "parent", "abstract" };

        foreach (var (key, value) in _entry.Mapping)
        {
            if (skipKeys.Contains(key))
                continue;

            if (key == "components")
                continue;

            var fieldRow = FieldControlFactory.CreateFieldRow(
                key,
                value,
                FieldSource.Local,
                _serializationManager,
                newValue => OnFieldEdited(key, newValue),
                () => ResetField(key));

            FieldsContainer.AddChild(fieldRow);
        }
    }

    /// <summary>
    /// Generic component population — works for any prototype with a ComponentRegistry.
    /// </summary>
    private void PopulateComponents(MappingDataNode? parentData)
    {
        ComponentsList.RemoveAllChildren();

        // Gather local components
        SequenceDataNode? localComps = null;
        if (_entry.Mapping != null && _entry.Mapping.TryGet("components", out var localCompNode))
            localComps = localCompNode as SequenceDataNode;

        // Gather inherited components
        SequenceDataNode? inheritedComps = null;
        if (parentData != null && parentData.TryGet("components", out var parentCompNode))
            inheritedComps = parentCompNode as SequenceDataNode;

        // Build a combined view: local overrides inherited
        var localByType = new Dictionary<string, MappingDataNode>();
        if (localComps != null)
        {
            foreach (var comp in localComps.Sequence.OfType<MappingDataNode>())
            {
                if (comp.TryGet("type", out var typeNode) && typeNode is ValueDataNode typeVal)
                    localByType[typeVal.Value] = comp;
            }
        }

        var inheritedByType = new Dictionary<string, MappingDataNode>();
        if (inheritedComps != null)
        {
            foreach (var comp in inheritedComps.Sequence.OfType<MappingDataNode>())
            {
                if (comp.TryGet("type", out var typeNode) && typeNode is ValueDataNode typeVal)
                    inheritedByType[typeVal.Value] = comp;
            }
        }

        // Merge: show all components (local first, then inherited-only)
        var allTypes = new List<string>();
        allTypes.AddRange(localByType.Keys);
        foreach (var key in inheritedByType.Keys)
        {
            if (!allTypes.Contains(key))
                allTypes.Add(key);
        }

        foreach (var compType in allTypes)
        {
            var isLocal = localByType.ContainsKey(compType);
            var mapping = isLocal
                ? localByType[compType]
                : inheritedByType.GetValueOrDefault(compType) ?? new MappingDataNode();

            // Resolve inherited component data for per-field source detection
            MappingDataNode? inheritedCompMapping = null;
            if (inheritedByType.TryGetValue(compType, out var inhComp))
                inheritedCompMapping = inhComp;

            var compCard = new ComponentCard(
                compType,
                mapping,
                inheritedCompMapping,
                isLocal,
                _serializationManager,
                _componentFactory);

            compCard.OnFieldChanged += (fieldTag, newValue) =>
            {
                OnFieldChanged?.Invoke($"components.{compType}.{fieldTag}", newValue);
            };

            compCard.OnRemoveRequested += () =>
            {
                RemoveComponent(compType);
            };

            ComponentsList.AddChild(compCard);
        }
    }

    private void OnAddComponentPressed()
    {
        if (_componentFactory == null)
            return;

        // Gather existing component names to exclude
        var existingTypes = new HashSet<string>();
        if (_entry.Mapping?.TryGet("components", out var compsNode) == true
            && compsNode is SequenceDataNode compsSeq)
        {
            foreach (var comp in compsSeq.Sequence.OfType<MappingDataNode>())
            {
                if (comp.TryGet("type", out var typeNode) && typeNode is ValueDataNode typeVal)
                    existingTypes.Add(typeVal.Value);
            }
        }

        var popup = new AddComponentPopup(_componentFactory, existingTypes);

        popup.OnComponentSelected += compName =>
        {
            AddComponent(compName);
        };

        UserInterfaceManager.WindowRoot.AddChild(popup);
        popup.OpenCentered();
    }

    private void AddComponent(string componentName)
    {
        // Ensure we have a local mapping
        _entry.Mapping ??= new MappingDataNode();

        // Ensure components sequence exists
        SequenceDataNode compsSeq;
        if (_entry.Mapping.TryGet("components", out var existing) && existing is SequenceDataNode seq)
        {
            compsSeq = seq;
        }
        else
        {
            compsSeq = new SequenceDataNode();
            _entry.Mapping["components"] = compsSeq;
        }

        // Add new component mapping
        var compMapping = new MappingDataNode();
        compMapping["type"] = new ValueDataNode(componentName);
        compsSeq.Add(compMapping);

        // Notify and refresh
        OnFieldChanged?.Invoke($"components.{componentName}", null);
        PopulateAllFields();
    }

    private void RemoveComponent(string componentName)
    {
        if (_entry.Mapping == null)
            return;

        if (!_entry.Mapping.TryGet("components", out var compsNode)
            || compsNode is not SequenceDataNode compsSeq)
            return;

        // Find and remove the component with matching type
        for (var i = 0; i < compsSeq.Sequence.Count; i++)
        {
            if (compsSeq.Sequence[i] is MappingDataNode comp
                && comp.TryGet("type", out var typeNode)
                && typeNode is ValueDataNode typeVal
                && typeVal.Value == componentName)
            {
                compsSeq.RemoveAt(i);
                break;
            }
        }

        // Clean up empty components sequence
        if (compsSeq.Sequence.Count == 0)
            _entry.Mapping.Remove("components");

        OnFieldChanged?.Invoke($"components.{componentName}", null);
        PopulateAllFields();
    }

    private void OnFieldEdited(string tag, object? newValue)
    {
        // When user edits a field, add it to the local mapping (making it local/overridden)
        _entry.UpdateField(tag, newValue, _serializationManager);
        OnFieldChanged?.Invoke(tag, newValue);
    }

    /// <summary>
    /// Called when a default field is overridden from the "(default)" button.
    /// Updates the mapping and refreshes the field display.
    /// </summary>
    private void OnFieldOverridden(string tag, object? newValue)
    {
        _entry.UpdateField(tag, newValue, _serializationManager);
        OnFieldChanged?.Invoke(tag, newValue);

        // Refresh to show the field as editable (local source)
        PopulateAllFields();
    }

    private void ResetField(string tag)
    {
        // Remove the field from local mapping, reverting to inherited/default
        _entry.Mapping?.Remove(tag);
        OnFieldReset?.Invoke(tag);

        // Re-render to update styling
        PopulateAllFields();
    }

    /// <summary>
    /// Rebuilds the field display. Call after parent changes or external edits.
    /// </summary>
    public void RefreshFields()
    {
        PopulateAllFields();
    }

    /// <summary>
    /// Sets validation error state on the card header and per-field indicators.
    /// </summary>
    public void SetHasErrors(bool hasErrors,
        string? errorSummary = null,
        Dictionary<string, string>? fieldErrors = null)
    {
        var oldFieldErrors = _fieldErrors;
        _fieldErrors = fieldErrors ?? new Dictionary<string, string>();

        if (hasErrors)
        {
            HeaderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#3d1f1f"),
                BorderColor = EditorMainControl.ErrorColor,
                BorderThickness = new Thickness(0, 0, 0, 2),
            };
            HeaderPanel.ToolTip = errorSummary ?? "This prototype has validation errors";
        }
        else
        {
            // Restore normal header
            var headerColor = _entry.IsAbstract
                ? Color.FromHex("#28292c")
                : Color.FromHex("#2d2f47");
            HeaderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = headerColor,
            };
            HeaderPanel.ToolTip = null;
        }

        // Re-render fields if error state changed (to show/hide per-field indicators)
        if (!FieldErrorsEqual(oldFieldErrors, _fieldErrors))
            PopulateAllFields();
    }

    private static bool FieldErrorsEqual(
        Dictionary<string, string> a,
        Dictionary<string, string> b)
    {
        if (a.Count != b.Count)
            return false;

        foreach (var (key, val) in a)
        {
            if (!b.TryGetValue(key, out var bVal) || val != bVal)
                return false;
        }

        return true;
    }

    #region Event Handlers

    private void OnIdChanged(LineEdit.LineEditEventArgs args)
    {
        _entry.Id = args.Text;
        OnFieldChanged?.Invoke("id", args.Text);
    }

    private void OnAbstractToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _entry.IsAbstract = args.Pressed;
        OnFieldChanged?.Invoke("abstract", args.Pressed);
    }

    private void OnApplyParent(BaseButton.ButtonEventArgs args)
    {
        ApplyParentChange();
    }

    private void ApplyParentChange()
    {
        var text = ParentEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
            _entry.Parents = null;
        else
            _entry.Parents = text.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);

        // Update the mapping
        if (_entry.Parents != null && _entry.Parents.Length > 0)
        {
            if (_entry.Parents.Length == 1)
            {
                if (_entry.Mapping != null)
                    _entry.Mapping["parent"] = new ValueDataNode(_entry.Parents[0]);
            }
            else
            {
                var seq = new SequenceDataNode();
                foreach (var p in _entry.Parents)
                {
                    seq.Add(new ValueDataNode(p));
                }

                if (_entry.Mapping != null)
                    _entry.Mapping["parent"] = seq;
            }
        }
        else
        {
            _entry.Mapping?.Remove("parent");
        }

        OnParentChanged?.Invoke(_entry.Parents);

        // Refresh fields with new inheritance
        PopulateAllFields();
    }

    private void OnCollapsePressed(BaseButton.ButtonEventArgs args)
    {
        _isCollapsed = !_isCollapsed;
        BodyContainer.Visible = !_isCollapsed;
        CollapseButton.Text = _isCollapsed ? ">" : "v";
    }

    private void OnHeaderRightClick(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIRightClick)
            return;

        args.Handle();

        var menu = new EditorContextMenu();

        menu.AddItem("Rename ID...",
            () =>
            {
                // Focus the ID editor for inline rename
                IdEdit.GrabKeyboardFocus();
            });

        menu.AddItem(_isCollapsed ? "Expand" : "Collapse",
            () =>
            {
                _isCollapsed = !_isCollapsed;
                BodyContainer.Visible = !_isCollapsed;
                CollapseButton.Text = _isCollapsed ? ">" : "v";
            });

        menu.AddSeparator();

        menu.AddItem("Delete prototype",
            () =>
            {
                OnDeleteRequested?.Invoke();
            },
            danger: true);

        UserInterfaceManager.ModalRoot.AddChild(menu);
        menu.OpenAtPosition(args.PointerLocation.Position);
    }

    #endregion
}
