using Content.Client.Stylesheets;
using Content.Editor.UI.FieldEditors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Editor.UI;

/// <summary>
/// Renders a single prototype as a card with a header (kind + ID + parent)
/// and a list of data field rows with type-appropriate editors.
/// Overridden fields show a colored left bar and a reset button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeCardControl : PanelContainer
{
    private static readonly Color CardBg = Color.FromHex("#1a1a2e");
    private static readonly Color HeaderBg = Color.FromHex("#252545");
    private static readonly Color BadgeBg = Color.FromHex("#3a3a5c");
    private static readonly Color OverrideBarColor = Color.FromHex("#4FC3F7");
    private static readonly Color RowAltBg = Color.FromHex("#1e1e36");

    /// <summary>
    /// Fired when the user edits a field value.
    /// Args: (prototypeId, fieldName, newValue).
    /// </summary>
    public event Action<string, string, string>? OnFieldEdited;

    /// <summary>
    /// Fired when the user resets an overridden field.
    /// Args: (prototypeId, fieldName).
    /// </summary>
    public event Action<string, string>? OnFieldReset;

    private string _prototypeId = "";

    public PrototypeCardControl()
    {
        RobustXamlLoader.Load(this);

        PanelOverride = new StyleBoxFlat(CardBg);
        HeaderPanel.PanelOverride = new StyleBoxFlat(HeaderBg);
        TypeBadgePanel.PanelOverride = new StyleBoxFlat(BadgeBg);
    }

    /// <summary>
    /// Populates the card with prototype data.
    /// </summary>
    public void Populate(
        string kind,
        string id,
        string? parent,
        bool isAbstract,
        List<EditorFieldData> fields)
    {
        _prototypeId = id;

        KindBadge.Text = kind;
        IdLabel.Text = id;
        ParentLabel.Text = parent != null ? $"parent: {parent}" : "";
        ParentLabel.Visible = parent != null;
        AbstractLabel.Visible = isAbstract;

        FieldsContainer.RemoveAllChildren();

        for (var i = 0; i < fields.Count; i++)
        {
            AddFieldRow(fields[i], i % 2 == 1);
        }
    }

    private void AddFieldRow(EditorFieldData field, bool altRow)
    {
        var row = new PanelContainer
        {
            HorizontalExpand = true,
        };

        if (altRow)
            row.PanelOverride = new StyleBoxFlat(RowAltBg);

        var rowBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 0,
        };

        // Override indicator bar — a real PanelContainer with a solid StyleBoxFlat
        var bar = new PanelContainer
        {
            MinWidth = 3,
            MaxWidth = 3,
            VerticalExpand = true,
        };

        if (field.IsOverridden)
        {
            bar.PanelOverride = new StyleBoxFlat(OverrideBarColor);
        }

        rowBox.AddChild(bar);

        // Field name label + required asterisk
        var nameBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            MinWidth = 180,
            MaxWidth = 180,
            SeparationOverride = 0,
        };

        var nameLabel = new Label
        {
            Text = field.Name,
            HorizontalExpand = true,
            Margin = new Thickness(field.IsRequired ? 2 : 8, 3, 4, 3),
            ClipText = true,
        };

        nameLabel.AddStyleClass(field.IsOverridden ? StyleClass.Highlight : StyleClass.LabelWeak);

        nameBox.AddChild(nameLabel);
        rowBox.AddChild(nameBox);

        if (field.IsRequired)
        {
            var asterisk = new Label
            {
                Text = "*",
                Margin = new Thickness(4, 3, 0, 3),
                FontColorOverride = Color.Red,
            };
            nameBox.AddChild(asterisk);
        }

        // Value editor — created by factory based on field type
        var editor = FieldEditorFactory.Create(field.FieldType);
        editor.SetValue(field.Value);
        editor.Control.HorizontalExpand = true;
        editor.Control.Margin = new Thickness(4, 2, 4, 2);

        var capturedName = field.Name;
        editor.OnValueChanged += newValue =>
        {
            OnFieldEdited?.Invoke(_prototypeId, capturedName, newValue);
        };

        rowBox.AddChild(editor.Control);

        // Reset button — only for overridden fields
        if (field.IsOverridden)
        {
            var resetBtn = new Label
            {
                Text = "↺",
                MinWidth = 24,
                Margin = new Thickness(2, 2, 6, 2),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Stop,
                ToolTip = "Reset to inherited value",
            };
            resetBtn.AddStyleClass(StyleClass.LabelWeak);

            resetBtn.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    OnFieldReset?.Invoke(_prototypeId, capturedName);
                    args.Handle();
                }
            };

            rowBox.AddChild(resetBtn);
        }

        row.AddChild(rowBox);
        FieldsContainer.AddChild(row);
    }
}

/// <summary>
/// Data for a single field row on a prototype card.
/// </summary>
public sealed class EditorFieldData
{
    /// <summary>
    /// YAML key / DataField tag name.
    /// </summary>
    public string Name { get; init; } = "";

    /// <summary>
    /// Display value as text.
    /// </summary>
    public string Value { get; set; } = "";

    /// <summary>
    /// Whether this field is locally overridden in the YAML file
    /// (as opposed to inherited or at C# default).
    /// </summary>
    public bool IsOverridden { get; set; }

    /// <summary>
    /// The C# <see cref="Type"/> of the field for editor selection, or null if unknown.
    /// </summary>
    public Type? FieldType { get; init; }

    /// <summary>
    /// Whether this field has <c>[DataField(required: true)]</c>.
    /// </summary>
    public bool IsRequired { get; init; }

    /// <summary>
    /// Declaration order from C# reflection (base class first).
    /// Used to keep a stable field order in the editor.
    /// </summary>
    public int Order { get; init; } = int.MaxValue;

    /// <summary>
    /// The inherited value (from parents or C# default), used for reset.
    /// </summary>
    public string InheritedValue { get; init; } = "";
}
