using System.IO;
using System.Linq;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Editor.UI;

/// <summary>
/// Left sidebar control that scans Resources/Prototypes/ directory
/// and displays a searchable, expandable file tree.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeBrowserControl : PanelContainer
{
    /// <summary>
    /// Fired when the user clicks on a .yml file in the tree.
    /// Argument is the absolute file path.
    /// </summary>
    public event Action<string>? OnFileSelected;

    private readonly string _prototypesRoot;
    private readonly Dictionary<string, bool> _expandedFolders = new();

    private string? _selectedFilePath;

    public PrototypeBrowserControl()
    {
        RobustXamlLoader.Load(this);

        RefreshButton.OnPressed += _ => RefreshTree();
        SearchBox.OnTextChanged += _ => RefreshTree();

        _prototypesRoot = Path.Combine(Directory.GetCurrentDirectory(), "Resources", "Prototypes");
        RefreshTree();
    }

    /// <summary>
    /// Rescans the file system and rebuilds the tree UI.
    /// </summary>
    private void RefreshTree()
    {
        FileList.RemoveAllChildren();

        if (!Directory.Exists(_prototypesRoot))
        {
            var errorLabel = new Label
            {
                Text = $"Not found:\n{_prototypesRoot}",
                Margin = new Thickness(12, 8),
            };
            errorLabel.AddStyleClass(StyleClass.Negative);
            FileList.AddChild(errorLabel);
            return;
        }

        var filter = SearchBox.Text.Trim() ?? "";
        BuildTree(_prototypesRoot, 0, filter);
    }

    /// <summary>
    /// Highlights the given file path as selected in the tree.
    /// </summary>
    public void SetSelectedFile(string? path)
    {
        _selectedFilePath = path;
        RefreshTree();
    }

    // ── Tree building ──

    private void BuildTree(string dirPath, int depth, string filter)
    {
        var dirs = Directory.GetDirectories(dirPath)
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var files = Directory.GetFiles(dirPath, "*.yml")
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        foreach (var dir in dirs)
        {
            var dirName = Path.GetFileName(dir);

            if (!string.IsNullOrEmpty(filter))
            {
                if (!DirectoryContainsMatch(dir, filter))
                    continue;

                AddFolderRow(dirName, depth, expanded: true, toggleAction: null);
                BuildTree(dir, depth + 1, filter);
            }
            else
            {
                var key = dir;
                _expandedFolders.TryGetValue(key, out var expanded);

                AddFolderRow(dirName,
                    depth,
                    expanded,
                    () =>
                    {
                        _expandedFolders[key] = !expanded;
                        RefreshTree();
                    });

                if (expanded)
                    BuildTree(dir, depth + 1, filter);
            }
        }

        foreach (var file in files)
        {
            var fileName = Path.GetFileName(file);

            if (!string.IsNullOrEmpty(filter)
                && !fileName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            AddFileRow(fileName, file, depth);
        }
    }

    private bool DirectoryContainsMatch(string dirPath, string filter)
    {
        return Directory.EnumerateFiles(dirPath, "*.yml", SearchOption.AllDirectories)
            .Any(f => Path.GetFileName(f).Contains(filter, StringComparison.OrdinalIgnoreCase));
    }

    private void AddFolderRow(string name, int depth, bool expanded, Action? toggleAction)
    {
        var arrow = expanded ? "▼" : "▶";
        var label = new Label
        {
            Text = $"{arrow}  {name}/",
            Margin = new Thickness(depth * 16 + 8, 3, 8, 3),
            HorizontalExpand = true,
            MouseFilter = toggleAction != null ? MouseFilterMode.Stop : MouseFilterMode.Ignore,
        };
        label.AddStyleClass(StyleClass.Highlight);

        if (toggleAction != null)
        {
            label.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    toggleAction();
                    args.Handle();
                }
            };
        }

        FileList.AddChild(label);
    }

    private void AddFileRow(string name, string fullPath, int depth)
    {
        var isSelected = string.Equals(_selectedFilePath, fullPath, StringComparison.OrdinalIgnoreCase);

        var row = new PanelContainer
        {
            HorizontalExpand = true,
        };

        if (isSelected)
            row.AddStyleClass(StyleClass.PanelLight);

        var label = new Label
        {
            Text = $"  {name}",
            Margin = new Thickness(depth * 16 + 20, 2, 8, 2),
            HorizontalExpand = true,
            MouseFilter = MouseFilterMode.Stop,
        };

        if (isSelected)
            label.AddStyleClass(StyleClass.Highlight);

        label.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                OnFileSelected?.Invoke(fullPath);
                args.Handle();
            }
        };

        row.AddChild(label);
        FileList.AddChild(row);
    }
}
