using System.Numerics;
using Content.Client.Stylesheets;
using Content.Editor.UI.FieldEditors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Serialization.Manager.Definition;
using Robust.Shared.Utility;

namespace Content.Editor.UI;

/// <summary>
/// Renders a single prototype as a card with a header (kind + ID + parent)
/// and a list of data field rows with type-appropriate editors.
/// Overridden fields show a colored left bar and a reset button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeCardControl : PanelContainer
{
    private static readonly Color CardBg = Color.FromHex("#1a1a2e");
    private static readonly Color HeaderBg = Color.FromHex("#252545");
    private static readonly Color BadgeBg = Color.FromHex("#3a3a5c");
    private static readonly Color OverrideBarColor = Color.FromHex("#4FC3F7");
    private static readonly Color RowAltBg = Color.FromHex("#1e1e36");

    private static readonly ResPath RefreshIconPath =
        new("/Textures/Interface/VerbIcons/refresh.svg.192dpi.png");

    /// <summary>
    /// Fired when the user edits a field value.
    /// Args: (prototypeId, fieldName, newValue).
    /// </summary>
    public event Action<string, string, string>? OnFieldEdited;

    /// <summary>
    /// Fired when the user resets an overridden field.
    /// Args: (prototypeId, fieldName).
    /// </summary>
    public event Action<string, string>? OnFieldReset;

    private string _prototypeId = "";
    private string _protoKind = "";

    public PrototypeCardControl()
    {
        RobustXamlLoader.Load(this);

        PanelOverride = new StyleBoxFlat(CardBg);
        HeaderPanel.PanelOverride = new StyleBoxFlat(HeaderBg);
        TypeBadgePanel.PanelOverride = new StyleBoxFlat(BadgeBg);
    }

    /// <summary>
    /// Populates the card with prototype data.
    /// </summary>
    public void Populate(
        string kind,
        string id,
        string? parent,
        bool isAbstract,
        List<EditorFieldData> fields)
    {
        _prototypeId = id;
        _protoKind = kind;

        KindBadge.Text = kind;
        IdLabel.Text = id;
        ParentLabel.Text = parent != null ? $"parent: {parent}" : "";
        ParentLabel.Visible = parent != null;
        AbstractLabel.Visible = isAbstract;

        FieldsContainer.RemoveAllChildren();

        for (var i = 0; i < fields.Count; i++)
        {
            AddFieldRow(fields[i], i % 2 == 1);
        }
    }

    private Texture? GetRefreshIcon()
    {
        try
        {
            var cache = IoCManager.Resolve<IResourceCache>();
            return cache.GetResource<TextureResource>(RefreshIconPath).Texture;
        }
        catch
        {
            return null;
        }
    }

    private Control CreateResetButton(string tooltip, Action onClick)
    {
        var icon = GetRefreshIcon();
        if (icon != null)
        {
            var btn = new TextureRect
            {
                Texture = icon,
                TextureScale = new Vector2(0.55f, 0.55f),
                MinWidth = 20,
                MinHeight = 20,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(2, 2, 6, 2),
                MouseFilter = MouseFilterMode.Stop,
                ToolTip = tooltip,
            };

            btn.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    onClick();
                    args.Handle();
                }
            };

            return btn;
        }

        // Fallback to text
        var label = new Label
        {
            Text = "↺",
            MinWidth = 24,
            Margin = new Thickness(2, 2, 6, 2),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = tooltip,
        };
        label.AddStyleClass(StyleClass.LabelWeak);

        label.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                onClick();
                args.Handle();
            }
        };

        return label;
    }

    private void AddFieldRow(EditorFieldData field, bool altRow)
    {
        var row = new PanelContainer
        {
            HorizontalExpand = true,
        };

        if (altRow)
            row.PanelOverride = new StyleBoxFlat(RowAltBg);

        var rowBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 0,
        };

        // Override indicator bar
        var bar = new PanelContainer
        {
            MinWidth = 3,
            MaxWidth = 3,
            VerticalExpand = true,
        };

        if (field.IsOverridden)
        {
            bar.PanelOverride = new StyleBoxFlat(OverrideBarColor);
        }

        rowBox.AddChild(bar);

        // Field name label + required asterisk
        var nameBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            MinWidth = 180,
            MaxWidth = 180,
            SeparationOverride = 0,
        };

        var nameLabel = new Label
        {
            Text = field.Name,
            HorizontalExpand = true,
            Margin = new Thickness(field.IsRequired ? 2 : 8, 3, 4, 3),
            ClipText = true,
        };

        nameLabel.AddStyleClass(field.IsOverridden ? StyleClass.Highlight : StyleClass.LabelWeak);

        nameBox.AddChild(nameLabel);
        rowBox.AddChild(nameBox);

        if (field.IsRequired)
        {
            var asterisk = new Label
            {
                Text = "*",
                Margin = new Thickness(4, 3, 0, 3),
                FontColorOverride = Color.Red,
            };
            nameBox.AddChild(asterisk);
        }

        // Value editor — pass context so editors like ComponentRegistryFieldEditor work
        var context = new EditorContext
        {
            PrototypeKind = _protoKind,
            PrototypeId = _prototypeId,
        };

        var editor = FieldEditorFactory.Create(field.FieldType, context);
        editor.SetValue(field.Value);

        if (field.ResolvedValue != null)
            editor.SetResolvedValue(field.ResolvedValue);

        editor.Control.HorizontalExpand = true;
        editor.Control.Margin = new Thickness(4, 2, 4, 2);

        var capturedName = field.Name;
        editor.OnValueChanged += newValue =>
        {
            OnFieldEdited?.Invoke(_prototypeId, capturedName, newValue);
        };

        rowBox.AddChild(editor.Control);

        // Reset button — only for overridden fields
        if (field.IsOverridden)
        {
            var capturedNameR = field.Name;
            var resetBtn = CreateResetButton("Reset to inherited value", () =>
            {
                OnFieldReset?.Invoke(_prototypeId, capturedNameR);
            });

            rowBox.AddChild(resetBtn);
        }

        row.AddChild(rowBox);
        FieldsContainer.AddChild(row);
    }
}

/// <summary>
/// Data for a single field row on a prototype card.
/// </summary>
public sealed class EditorFieldData
{
    /// <summary>
    /// YAML key / DataField tag name.
    /// </summary>
    public string Name { get; init; } = "";

    /// <summary>
    /// Display value as text.
    /// </summary>
    public string Value { get; set; } = "";

    /// <summary>
    /// Whether this field is locally overridden in the YAML file
    /// (as opposed to inherited or at C# default).
    /// </summary>
    public bool IsOverridden { get; set; }

    /// <summary>
    /// The C# <see cref="Type"/> of the field for editor selection, or null if unknown.
    /// </summary>
    public Type? FieldType { get; init; }

    /// <summary>
    /// Whether this field has <c>[DataField(required: true)]</c>.
    /// </summary>
    public bool IsRequired { get; init; }

    /// <summary>
    /// Declaration order from C# reflection (base class first).
    /// Used to keep a stable field order in the editor.
    /// </summary>
    public int Order { get; init; } = int.MaxValue;

    /// <summary>
    /// Inheritance behavior: Default, Always (merge), or Never (don't propagate).
    /// </summary>
    public InheritanceBehavior Inheritance { get; init; } = InheritanceBehavior.Default;

    /// <summary>
    /// The inherited value (from parents or C# default), used for reset.
    /// </summary>
    public string InheritedValue { get; init; } = "";

    /// <summary>
    /// For AlwaysPushInheritance fields: the full post-inheritance (resolved) value.
    /// Null for most fields. Used by editors like ComponentRegistryFieldEditor
    /// to display inherited data while tracking local edits separately.
    /// </summary>
    public string? ResolvedValue { get; init; }
}
