using System.Linq;
using Content.Editor.Prototype;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Markdown;
using Robust.Shared.Serialization.Markdown.Mapping;
using Robust.Shared.Serialization.Markdown.Sequence;
using Robust.Shared.Serialization.Markdown.Value;

namespace Content.Editor.UI;

/// <summary>
/// A styled card representing a single prototype entry.
/// Shows ALL fields from the prototype type (local, inherited, default).
/// Supports override visualization, reset buttons, and generic component handling.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PrototypeCard : PanelContainer
{
    private readonly PrototypeEntry _entry;
    private readonly IPrototypeManager _prototypeManager;
    private readonly ISerializationManager _serializationManager;
    private bool _isCollapsed;

    /// <summary>
    /// Fired when a field value is changed. Args: (fieldTag, newValue).
    /// </summary>
    public event Action<string, object?>? OnFieldChanged;

    /// <summary>
    /// Fired when a field is reset (removed from local mapping).
    /// </summary>
    public event Action<string>? OnFieldReset;

    /// <summary>
    /// Fired when the parent is changed.
    /// </summary>
    public event Action<string[]?>? OnParentChanged;

    public PrototypeCard(
        PrototypeEntry entry,
        IPrototypeManager prototypeManager,
        ISerializationManager serializationManager)
    {
        RobustXamlLoader.Load(this);

        _entry = entry;
        _prototypeManager = prototypeManager;
        _serializationManager = serializationManager;

        ApplyCardStyling();

        // Set up header data
        TypeBadge.Text = entry.TypeString.ToUpperInvariant();
        IdEdit.Text = entry.Id ?? "";

        // Only show abstract toggle for IInheritingPrototype
        if (entry.PrototypeType != null && PrototypeReflector.SupportsInheritance(entry.PrototypeType))
        {
            AbstractToggle.Visible = true;
            AbstractToggle.Pressed = entry.IsAbstract;

            // Show parent editor
            ParentPanel.Visible = true;
            ParentEdit.Text = entry.Parents != null
                ? string.Join(", ", entry.Parents)
                : "";
        }

        // Wire up events
        IdEdit.OnTextEntered += OnIdChanged;
        AbstractToggle.OnToggled += OnAbstractToggled;
        CollapseButton.OnPressed += OnCollapsePressed;
        ApplyParentButton.OnPressed += OnApplyParent;

        // Populate fields
        PopulateAllFields();
    }

    private void ApplyCardStyling()
    {
        // Card outer container
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = EditorMainControl.BgSecondary,
            BorderColor = EditorMainControl.Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
        };

        // Header: accent tint for normal, gray for abstract
        var headerColor = _entry.IsAbstract
            ? Color.FromHex("#28292c")
            : Color.FromHex("#2d2f47");
        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = headerColor,
        };

        // Type badge: pill-style
        TypeBadgePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = _entry.IsAbstract
                ? Color.FromHex("#666666")
                : EditorMainControl.Accent,
        };

        // Parent bar: subtle blue tint
        ParentPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1d2230"),
            BorderColor = EditorMainControl.BorderSubtle,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        // Components section header: top border separator
        CompHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BorderColor = EditorMainControl.Border,
            BorderThickness = new Thickness(0, 2, 0, 0),
        };
    }

    /// <summary>
    /// Populates ALL fields from the prototype type, plus any extra YAML keys.
    /// Shows each field with its source (local/inherited/default).
    /// </summary>
    private void PopulateAllFields()
    {
        FieldsContainer.RemoveAllChildren();
        ComponentsList.RemoveAllChildren();
        ComponentsSection.Visible = false;

        if (_entry.PrototypeType == null)
        {
            // Unknown type — just show raw YAML fields
            PopulateRawFields();
            return;
        }

        // Resolve parent data for inheritance display
        var parentData = InheritanceResolver.ResolveParentData(_entry, _prototypeManager);

        // Get all metadata fields for this prototype type
        var metaFields = PrototypeReflector.GetFields(_entry.PrototypeType);
        var handledTags = new HashSet<string> { "type", "id", "parent", "abstract" };

        // Render metadata fields first (in declaration order)
        foreach (var meta in metaFields)
        {
            // Components handled separately
            if (meta.IsComponentRegistry)
            {
                ComponentsSection.Visible = true;
                PopulateComponents(parentData);
                handledTags.Add(meta.Tag);
                continue;
            }

            handledTags.Add(meta.Tag);

            var source = InheritanceResolver.GetFieldSource(meta.Tag, _entry.Mapping, parentData);
            var valueNode = InheritanceResolver.GetFieldValue(meta.Tag, _entry.Mapping, parentData);

            Action? onReset = null;
            if (source == FieldSource.Local)
            {
                var tag = meta.Tag;
                onReset = () => ResetField(tag);
            }

            var fieldRow = FieldControlFactory.CreateFieldRow(
                meta.Tag,
                valueNode,
                source,
                _serializationManager,
                newValue => OnFieldEdited(meta.Tag, newValue),
                onReset);

            FieldsContainer.AddChild(fieldRow);
        }

        // Render any extra YAML keys not covered by metadata
        if (_entry.Mapping != null)
        {
            foreach (var (key, value) in _entry.Mapping)
            {
                if (handledTags.Contains(key))
                    continue;

                if (key == "components")
                    continue;

                var fieldRow = FieldControlFactory.CreateFieldRow(
                    key,
                    value,
                    FieldSource.Local,
                    _serializationManager,
                    newValue => OnFieldEdited(key, newValue),
                    () => ResetField(key));

                FieldsContainer.AddChild(fieldRow);
            }
        }

        // Show inherited-only fields that are in parent data but not in metadata
        if (parentData != null)
        {
            foreach (var (key, value) in parentData)
            {
                if (handledTags.Contains(key))
                    continue;

                if (key == "components")
                    continue;

                handledTags.Add(key);

                var source = InheritanceResolver.GetFieldSource(key, _entry.Mapping, parentData);
                var valueNode = InheritanceResolver.GetFieldValue(key, _entry.Mapping, parentData);

                var fieldRow = FieldControlFactory.CreateFieldRow(
                    key,
                    valueNode,
                    source,
                    _serializationManager,
                    newValue => OnFieldEdited(key, newValue));

                FieldsContainer.AddChild(fieldRow);
            }
        }
    }

    private void PopulateRawFields()
    {
        if (_entry.Mapping == null)
            return;

        var skipKeys = new HashSet<string> { "type", "id", "parent", "abstract" };

        foreach (var (key, value) in _entry.Mapping)
        {
            if (skipKeys.Contains(key))
                continue;

            if (key == "components")
                continue;

            var fieldRow = FieldControlFactory.CreateFieldRow(
                key,
                value,
                FieldSource.Local,
                _serializationManager,
                newValue => OnFieldEdited(key, newValue),
                () => ResetField(key));

            FieldsContainer.AddChild(fieldRow);
        }
    }

    /// <summary>
    /// Generic component population — works for any prototype with a ComponentRegistry.
    /// </summary>
    private void PopulateComponents(MappingDataNode? parentData)
    {
        ComponentsList.RemoveAllChildren();

        // Gather local components
        SequenceDataNode? localComps = null;
        if (_entry.Mapping != null && _entry.Mapping.TryGet("components", out var localCompNode))
            localComps = localCompNode as SequenceDataNode;

        // Gather inherited components
        SequenceDataNode? inheritedComps = null;
        if (parentData != null && parentData.TryGet("components", out var parentCompNode))
            inheritedComps = parentCompNode as SequenceDataNode;

        // Build a combined view: local overrides inherited
        var localByType = new Dictionary<string, MappingDataNode>();
        if (localComps != null)
        {
            foreach (var comp in localComps.Sequence.OfType<MappingDataNode>())
            {
                if (comp.TryGet("type", out var typeNode) && typeNode is ValueDataNode typeVal)
                    localByType[typeVal.Value] = comp;
            }
        }

        var inheritedByType = new Dictionary<string, MappingDataNode>();
        if (inheritedComps != null)
        {
            foreach (var comp in inheritedComps.Sequence.OfType<MappingDataNode>())
            {
                if (comp.TryGet("type", out var typeNode) && typeNode is ValueDataNode typeVal)
                    inheritedByType[typeVal.Value] = comp;
            }
        }

        // Merge: show all components (local first, then inherited-only)
        var allTypes = new List<string>();
        allTypes.AddRange(localByType.Keys);
        foreach (var key in inheritedByType.Keys)
        {
            if (!allTypes.Contains(key))
                allTypes.Add(key);
        }

        foreach (var compType in allTypes)
        {
            var isLocal = localByType.ContainsKey(compType);
            var mapping = isLocal
                ? localByType[compType]
                : inheritedByType.GetValueOrDefault(compType) ?? new MappingDataNode();

            // Resolve inherited component data for per-field source detection
            MappingDataNode? inheritedCompMapping = null;
            if (inheritedByType.TryGetValue(compType, out var inhComp))
                inheritedCompMapping = inhComp;

            var compCard = new ComponentCard(
                compType,
                mapping,
                inheritedCompMapping,
                isLocal,
                _serializationManager);

            compCard.OnFieldChanged += (fieldTag, newValue) =>
            {
                OnFieldChanged?.Invoke($"components.{compType}.{fieldTag}", newValue);
            };

            ComponentsList.AddChild(compCard);
        }
    }

    private void OnFieldEdited(string tag, object? newValue)
    {
        // When user edits a field, add it to the local mapping (making it local/overridden)
        _entry.UpdateField(tag, newValue, _serializationManager);
        OnFieldChanged?.Invoke(tag, newValue);
    }

    private void ResetField(string tag)
    {
        // Remove the field from local mapping, reverting to inherited/default
        _entry.Mapping?.Remove(tag);
        OnFieldReset?.Invoke(tag);

        // Re-render to update styling
        PopulateAllFields();
    }

    /// <summary>
    /// Rebuilds the field display. Call after parent changes or external edits.
    /// </summary>
    public void RefreshFields()
    {
        PopulateAllFields();
    }

    #region Event Handlers

    private void OnIdChanged(LineEdit.LineEditEventArgs args)
    {
        _entry.Id = args.Text;
        OnFieldChanged?.Invoke("id", args.Text);
    }

    private void OnAbstractToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _entry.IsAbstract = args.Pressed;
        OnFieldChanged?.Invoke("abstract", args.Pressed);
    }

    private void OnApplyParent(BaseButton.ButtonEventArgs args)
    {
        var text = ParentEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
        {
            _entry.Parents = null;
        }
        else
        {
            _entry.Parents = text.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        }

        // Update the mapping
        if (_entry.Parents != null && _entry.Parents.Length > 0)
        {
            if (_entry.Parents.Length == 1)
                _entry.Mapping?["parent"] = new ValueDataNode(_entry.Parents[0]);
            else
            {
                var seq = new SequenceDataNode();
                foreach (var p in _entry.Parents)
                    seq.Add(new ValueDataNode(p));
                if (_entry.Mapping != null)
                    _entry.Mapping["parent"] = seq;
            }
        }
        else
        {
            _entry.Mapping?.Remove("parent");
        }

        OnParentChanged?.Invoke(_entry.Parents);

        // Refresh fields with new inheritance
        PopulateAllFields();
    }

    private void OnCollapsePressed(BaseButton.ButtonEventArgs args)
    {
        _isCollapsed = !_isCollapsed;
        BodyContainer.Visible = !_isCollapsed;
        CollapseButton.Text = _isCollapsed ? ">" : "v";
    }

    #endregion
}
