using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Editor.UI;

/// <summary>
/// Bottom status bar displaying current file info and messages.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StatusBarControl : PanelContainer
{
    public StatusBarControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Displays an error message on the right side of the status bar.
    /// </summary>
    public void ShowError(string message)
    {
        MessageLabel.Text = message;
        MessageLabel.RemoveStyleClass(StyleClass.LabelSubText);
        MessageLabel.AddStyleClass(StyleClass.Negative);
    }

    /// <summary>
    /// Displays an info message on the right side.
    /// </summary>
    public void ShowMessage(string message)
    {
        MessageLabel.Text = message;
        MessageLabel.RemoveStyleClass(StyleClass.Negative);
        MessageLabel.AddStyleClass(StyleClass.LabelSubText);
    }

    /// <summary>
    /// Clears the right-side message.
    /// </summary>
    public void ClearMessage()
    {
        MessageLabel.Text = "";
    }
}
