using System.IO;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Editor.UI;

/// <summary>
/// Horizontal scrollable tab strip for open files.
/// Each tab displays the file name and a close button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TabBarControl : PanelContainer
{
    /// <summary>
    /// Fired when the user selects a tab. Argument is the file path.
    /// </summary>
    public event Action<string>? OnTabSelected;

    /// <summary>
    /// Fired when the user closes a tab. Argument is the file path.
    /// </summary>
    public event Action<string>? OnTabClosed;

    private readonly List<string> _openPaths = new();
    private readonly HashSet<string> _dirtyPaths = new(StringComparer.OrdinalIgnoreCase);
    private string? _activePath;

    public TabBarControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Gets the list of currently open file paths.
    /// </summary>
    public IReadOnlyList<string> OpenPaths => _openPaths;

    /// <summary>
    /// Gets the currently active file path, or null if none.
    /// </summary>
    public string? ActivePath => _activePath;

    /// <summary>
    /// Activates the tab for the given file. Creates a new tab if one doesn't exist.
    /// </summary>
    public void OpenTab(string filePath)
    {
        if (!_openPaths.Contains(filePath))
            _openPaths.Add(filePath);

        _activePath = filePath;
        RebuildTabs();
    }

    /// <summary>
    /// Sets or clears the dirty indicator for the given file path.
    /// </summary>
    public void SetDirty(string filePath, bool isDirty)
    {
        if (isDirty)
            _dirtyPaths.Add(filePath);
        else
            _dirtyPaths.Remove(filePath);

        RebuildTabs();
    }

    /// <summary>
    /// Closes the tab for the given file path and activates an adjacent tab.
    /// </summary>
    public void CloseTab(string filePath)
    {
        var idx = _openPaths.IndexOf(filePath);
        if (idx < 0)
            return;

        _openPaths.RemoveAt(idx);
        _dirtyPaths.Remove(filePath);

        if (_openPaths.Count > 0)
        {
            var newIdx = Math.Min(idx, _openPaths.Count - 1);
            _activePath = _openPaths[newIdx];
        }
        else
        {
            _activePath = null;
        }

        RebuildTabs();
    }

    private void RebuildTabs()
    {
        TabStrip.RemoveAllChildren();

        foreach (var path in _openPaths)
        {
            var isActive = string.Equals(path, _activePath, StringComparison.OrdinalIgnoreCase);
            var isDirty = _dirtyPaths.Contains(path);
            var fileName = Path.GetFileName(path) + (isDirty ? " *" : "");

            var tabPanel = new PanelContainer
            {
                MinHeight = 30,
            };
            tabPanel.AddStyleClass(isActive ? StyleClass.PanelLight : StyleClass.PanelDark);

            var tabBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 2, 4, 2),
                SeparationOverride = 6,
            };

            var nameLabel = new Label
            {
                Text = fileName,
                MouseFilter = MouseFilterMode.Stop,
            };

            if (!isActive)
                nameLabel.AddStyleClass(StyleClass.LabelWeak);

            var capturedPath = path;
            nameLabel.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    OnTabSelected?.Invoke(capturedPath);
                    args.Handle();
                }
            };

            var closeLabel = new Label
            {
                Text = "✕",
                MouseFilter = MouseFilterMode.Stop,
                MinWidth = 18,
                Margin = new Thickness(2, 0, 2, 0),
            };
            closeLabel.AddStyleClass(StyleClass.LabelWeak);

            closeLabel.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    OnTabClosed?.Invoke(capturedPath);
                    args.Handle();
                }
            };

            tabBox.AddChild(nameLabel);
            tabBox.AddChild(closeLabel);
            tabPanel.AddChild(tabBox);
            TabStrip.AddChild(tabPanel);
        }
    }
}
