- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingShirtBase
  categories: [ ForkFiltered ]
  name: shirt
  description: Cover up your nakedness!
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - shirt
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingPantsBase
  categories: [ ForkFiltered ]
  name: pants
  description: Pants to cover my thighs from the cold.
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - pants
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingCloakBase
  categories: [ ForkFiltered ]
  name: cloak
  description: TODO
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    equipWhileMoving: true
    slots:
    - cloak
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingHeadBase
  categories: [ ForkFiltered ]
  name: head
  description: TODO
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    equipWhileMoving: true
    slots:
    - head
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingShoesBase
  categories: [ ForkFiltered ]
  name: shoes
  description: TODO
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - feet
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingGlovesBase
  categories: [ ForkFiltered ]
  name: gloves
  description: TODO
  components:
  - type: Clothing
    equipDelay: 0.5
    unequipDelay: 0.5
    equipWhileMoving: true
    slots:
    - gloves
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingBackContainerBase
  categories: [ ForkFiltered ]
  components:
  - type: Item
    size: Huge
  - type: Sprite
    sprite: _CE/Clothing/Back/Backpacks/leather.rsi
    state: icon
  - type: Clothing
    equipDelay: 0.4
    unequipDelay: 0.2
    slots:
    - back
    quickEquip: false
    breakOnMove: false
  - type: Storage
    grid:
    - 0,0,6,3
    maxItemSize: Huge
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UseDelay
    delay: 0.5
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
