using Content.Client.Message;
using Content.Shared._CE.Skills.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.SkillsUpgradeable.UI;

[GenerateTypedNameReferences]
public sealed partial class CESkillUpgradeEntry : PanelContainer
{
    public ProtoId<CESkillPrototype> SkillId { get; private set; }

    public event Action<ProtoId<CESkillPrototype>>? OnSkillSelected;

    public CESkillUpgradeEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.OnPressed += _ => OnSkillSelected?.Invoke(SkillId);
    }

    public void SetData(
        ProtoId<CESkillPrototype> skillId,
        string name,
        string description,
        Robust.Client.Graphics.Texture? icon)
    {
        SkillId = skillId;
        SkillName.SetMessage(name);
        SkillDesc.SetMarkup(description);

        if (icon != null)
            SkillIcon.Texture = icon;
    }
}
