using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Skills;
using Content.Shared._CE.Skills.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.SkillsUpgradeable.UI;

[GenerateTypedNameReferences]
public sealed partial class CESkillUpgradeWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private readonly SpriteSystem _sprite;
    private readonly CESharedSkillSystem _skillSystem;

    public event Action<ProtoId<CESkillPrototype>>? OnSkillSelected;

    public CESkillUpgradeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
        _skillSystem = _entManager.System<CESharedSkillSystem>();
    }

    public void Populate(HashSet<ProtoId<CESkillPrototype>> skills, int targetLevel)
    {
        LevelLabel.Text = Loc.GetString("ce-skill-upgrade-level-label", ("level", targetLevel));
        SkillsList.RemoveAllChildren();

        foreach (var skillId in skills)
        {
            var name = _skillSystem.GetSkillName(skillId);
            var desc = _skillSystem.GetSkillDescription(skillId);

            Robust.Client.Graphics.Texture? icon = null;
            var iconSpec = _skillSystem.GetSkillIcon(skillId);
            if (iconSpec != null)
                icon = _sprite.Frame0(iconSpec);

            var entry = new CESkillUpgradeEntry();
            entry.SetData(skillId, name, desc, icon);
            entry.OnSkillSelected += skillProtoId => OnSkillSelected?.Invoke(skillProtoId);

            SkillsList.AddChild(entry);
        }
    }
}
