using System.Numerics;
using Content.Client._CE.UserInterface.Systems.NodeTree;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.Procedural.Overview;

/// <summary>
/// Reusable side-panel + node-graph fragment used by both the admin dungeon overview
/// and the player wayfinding-stone overview. The control is purely presentational —
/// callers construct <see cref="CEDungeonOverviewLevelView"/>s and pass them via
/// <see cref="UpdateState"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEDungeonOverviewControl : BoxContainer
{
    /// <summary>
    /// One <c>uiPosition</c> unit in the prototype equals half a rendered sprite.
    /// </summary>
    private const float PositionUnit = 36f;

    private static readonly ResPath NodeTreeRsi = new("/Textures/_CE/Interface/NodeTree/demiplane_map.rsi");

    /// <summary>
    /// Raised when the user clicks a teleport button next to a player entry.
    /// Only fires when <see cref="EnableTeleport"/> is true and the underlying entry
    /// has a non-default <see cref="CEDungeonOverviewPlayerView.Entity"/>.
    /// </summary>
    public event Action<NetEntity>? OnTeleportRequested;

    /// <summary>
    /// When true, player entries are rendered as buttons that fire
    /// <see cref="OnTeleportRequested"/> on click. When false they are plain labels.
    /// </summary>
    public bool EnableTeleport { get; set; }

    /// <summary>
    /// Localization id used for the side panel header above the per-level details.
    /// Falls back to the graph header if not set.
    /// </summary>
    public string DetailsHeaderLocId { get; set; } = "ce-dungeon-overview-details-header";

    /// <summary>
    /// Localization id used for the header above the graph panel.
    /// </summary>
    public string GraphHeaderLocId { get; set; } = "ce-dungeon-overview-graph-header";

    private IReadOnlyList<CEDungeonOverviewLevelView> _levels = Array.Empty<CEDungeonOverviewLevelView>();
    private string? _currentLevelId;
    private string? _selectedLevelId;

    public CEDungeonOverviewControl()
    {
        RobustXamlLoader.Load(this);

        GraphControl.OnNodeSelected += OnNodeSelected;
        GraphControl.OnOffsetChanged += offset =>
        {
            // Match the parallax behaviour of the skill tree window.
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000);
        };

        ClearSelection();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ApplyHeaders();
    }

    private void ApplyHeaders()
    {
        DetailsHeader.Text = Loc.GetString(DetailsHeaderLocId);
        GraphHeader.Text = Loc.GetString(GraphHeaderLocId);
    }

    public void UpdateState(IReadOnlyList<CEDungeonOverviewLevelView> levels, string? currentLevelId)
    {
        _levels = levels;
        _currentLevelId = currentLevelId;
        ApplyHeaders();

        var nodes = new HashSet<CENodeTreeElement>();
        var edges = new HashSet<(string, string)>();

        var defaultIcon = new SpriteSpecifier.Rsi(NodeTreeRsi, "center");

        foreach (var level in levels)
        {
            var isCurrent = currentLevelId == level.Id;

            var node = new CENodeTreeElement(
                nodeKey: level.Id,
                gained: level.PlayerCount > 0,
                active: isCurrent,
                uiPosition: new Vector2(level.UIPosition.X, level.UIPosition.Y) * PositionUnit,
                icon: level.Icon ?? defaultIcon,
                label: level.PlayerCount > 0 ? level.PlayerCount.ToString() : null);

            nodes.Add(node);

            foreach (var target in level.Exits)
                edges.Add((level.Id, target));
        }

        var uiState = new CENodeTreeUiState(
            nodes,
            edges,
            frameIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "frame"),
            hoveredIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "hovered"),
            selectedIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "selected"),
            learnedIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "learned"))
        {
            DirectedEdges = true,
        };
        GraphControl.UpdateState(uiState);

        // Preserve selection if possible.
        if (_selectedLevelId != null && FindLevel(_selectedLevelId) != null)
            ShowLevelDetails(_selectedLevelId);
        else
            ClearSelection();
    }

    private CEDungeonOverviewLevelView? FindLevel(string id)
    {
        foreach (var l in _levels)
        {
            if (l.Id == id)
                return l;
        }
        return null;
    }

    private void OnNodeSelected(CENodeTreeElement? node)
    {
        if (node == null)
        {
            ClearSelection();
            return;
        }

        _selectedLevelId = node.NodeKey;
        ShowLevelDetails(node.NodeKey);
    }

    private void ClearSelection()
    {
        _selectedLevelId = null;
        LevelName.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("ce-dungeon-overview-no-selection")));
        LevelDesc.SetMessage(FormattedMessage.FromMarkupPermissive(string.Empty));
        DetailsContainer.RemoveAllChildren();
    }

    private void ShowLevelDetails(string levelId)
    {
        var level = FindLevel(levelId);
        if (level == null)
        {
            ClearSelection();
            return;
        }

        var nameText = !string.IsNullOrEmpty(level.NameLocId)
            ? Loc.GetString(level.NameLocId)
            : level.Id;
        LevelName.SetMessage(FormattedMessage.FromMarkupPermissive($"[head=2]{nameText}[/head]"));

        LevelDesc.SetMessage(FormattedMessage.FromMarkupPermissive(
            !string.IsNullOrEmpty(level.DescLocId)
                ? Loc.GetString(level.DescLocId)
                : string.Empty));

        DetailsContainer.RemoveAllChildren();

        // No instance breakdown: show a simple total players line.
        if (level.Instances == null)
        {
            DetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ce-dungeon-overview-total-players", ("count", level.PlayerCount)),
                StyleClasses = { "LabelKeyText" },
            });
            return;
        }

        if (level.Instances.Count == 0)
        {
            DetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ce-dungeon-overview-no-instances"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        var idx = 1;
        foreach (var inst in level.Instances)
        {
            var instHeader = new Label
            {
                Text = Loc.GetString("ce-dungeon-overview-instance-header",
                    ("index", idx++),
                    ("players", inst.PlayerCount)),
                StyleClasses = { "LabelKeyText" },
                Margin = new Thickness(0, 5, 0, 2),
            };
            DetailsContainer.AddChild(instHeader);

            if (inst.Players == null)
                continue;

            if (inst.Players.Count == 0)
            {
                DetailsContainer.AddChild(new Label
                {
                    Text = Loc.GetString("ce-dungeon-overview-instance-empty"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(10, 0, 0, 0),
                });
                continue;
            }

            foreach (var player in inst.Players)
            {
                var text = Loc.GetString("ce-dungeon-overview-player-entry",
                    ("character", string.IsNullOrWhiteSpace(player.CharacterName) ? "?" : player.CharacterName),
                    ("account", string.IsNullOrWhiteSpace(player.AccountName) ? "?" : player.AccountName));

                if (EnableTeleport)
                {
                    var button = new Button
                    {
                        Text = text,
                        StyleClasses = { "OpenBoth" },
                        Margin = new Thickness(10, 0, 0, 2),
                        HorizontalExpand = true,
                    };
                    var target = player.Entity;
                    button.OnPressed += _ => OnTeleportRequested?.Invoke(target);
                    DetailsContainer.AddChild(button);
                }
                else
                {
                    DetailsContainer.AddChild(new Label
                    {
                        Text = text,
                        Margin = new Thickness(10, 0, 0, 2),
                    });
                }
            }
        }
    }
}
