using Content.Shared._CE.Procedural.Overview;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Procedural.Overview;

[GenerateTypedNameReferences]
public sealed partial class CEPlayerDungeonOverviewWindow : DefaultWindow
{
    public CEPlayerDungeonOverviewWindow()
    {
        RobustXamlLoader.Load(this);

        OverviewControl.EnableTeleport = false;
        OverviewControl.DetailsHeaderLocId = "ce-player-dungeon-overview-details-header";
        OverviewControl.GraphHeaderLocId = "ce-player-dungeon-overview-graph-header";
    }

    public void UpdateState(CEPlayerDungeonOverviewState state)
    {
        var levels = new List<CEDungeonOverviewLevelView>(state.Levels.Count);
        foreach (var level in state.Levels)
        {
            levels.Add(new CEDungeonOverviewLevelView
            {
                Id = level.Id,
                NameLocId = level.NameLocId,
                DescLocId = level.DescLocId,
                UIPosition = level.UIPosition,
                Icon = level.Icon,
                Stable = level.Stable,
                Exits = level.Exits,
                PlayerCount = level.PlayerCount,
                // null = no per-instance breakdown — only total counts shown.
                Instances = null,
            });
        }

        OverviewControl.UpdateState(levels, state.CurrentLevelId);
    }
}
