using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEBossHealthBarUI : UIWidget
{
    private const string BossRsiPath = "/Textures/_CE/Interface/HealthMana/boss.rsi";
    private const float TextureScale = 3f;
    private const float GhostLerpSpeed = 0.05f;

    [Dependency] private IResourceCache _resCache = default!;

    private Texture? _emptyTex;
    private Texture? _filledTex;
    private Texture? _whiteTex;

    private float _filledRatio = 1f;
    private float _ghostRatio = 1f;

    public CEBossHealthBarUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadTextures();

        if (_emptyTex != null)
        {
            var barW = _emptyTex.Width * TextureScale;
            var barH = _emptyTex.Height * TextureScale;
            MinWidth = barW;
            SetWidth = barW;
            // BarArea reserves the exact bar height; BoxContainer stacks label above it.
            BarArea.MinHeight = barH;
            BarArea.SetHeight = barH;
            BarArea.MinWidth = barW;
        }

        var font = new VectorFont(
            _resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 24);
        BossNameLabel.FontOverride = font;
        BossNameLabel.FontColorOverride = Color.White;
    }

    private void LoadTextures()
    {
        if (!_resCache.TryGetResource<RSIResource>(new ResPath(BossRsiPath), out var rsi))
            return;

        if (rsi.RSI.TryGetState("empty", out var emptyState))
            _emptyTex = emptyState.Frame0;

        if (rsi.RSI.TryGetState("filled", out var filledState))
            _filledTex = filledState.Frame0;

        if (rsi.RSI.TryGetState("white", out var whiteState))
            _whiteTex = whiteState.Frame0;
    }

    /// <summary>
    /// Update the bar with the current aggregated health ratio, frame delta for lerp, and optional boss name.
    /// </summary>
    /// <param name="targetRatio">Current HP / Max HP (0..1).</param>
    /// <param name="deltaTime">Frame delta seconds for advancing the ghost bar lerp.</param>
    /// <param name="bossName">Boss entity name to display above the bar, or null to hide the label.</param>
    public void SetData(float targetRatio, float deltaTime, string? bossName)
    {
        targetRatio = Math.Clamp(targetRatio, 0f, 1f);

        // If health went up (heal), snap ghost immediately to the new higher value.
        if (targetRatio > _filledRatio)
            _ghostRatio = targetRatio;

        _filledRatio = targetRatio;

        // Lerp ghost bar down toward the filled bar.
        if (_ghostRatio > _filledRatio)
            _ghostRatio = MathF.Max(_filledRatio, _ghostRatio - deltaTime * GhostLerpSpeed);

        // Always set text (empty string when no name) so label stays in layout and bar position never jumps.
        BossNameLabel.Text = bossName ?? string.Empty;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_emptyTex == null)
            return;

        // BarArea is laid out by the BoxContainer directly below the label.
        // Use its pixel position and size for exact bar placement.
        var barOffsetY = BarArea.PixelPosition.Y;
        var barPxH = BarArea.PixelSize.Y;
        var totalPxW = PixelSize.X;

        if (barPxH <= 0)
            return;

        var barRect = UIBox2.FromDimensions(new Vector2(0, barOffsetY), new Vector2(totalPxW, barPxH));

        // 1. Empty background.
        handle.DrawTextureRect(_emptyTex, barRect);

        // 2. White "ghost" bar that slowly drains toward the filled ratio.
        if (_whiteTex != null && _ghostRatio > 0f)
        {
            var ghostW = totalPxW * _ghostRatio;
            var destGhost = UIBox2.FromDimensions(new Vector2(0, barOffsetY), new Vector2(ghostW, barPxH));
            var srcGhostW = _whiteTex.Width * _ghostRatio;
            var srcGhost = UIBox2.FromDimensions(Vector2.Zero, new Vector2(srcGhostW, _whiteTex.Height));
            handle.DrawTextureRectRegion(_whiteTex, destGhost, srcGhost);
        }

        // 3. Filled bar clipped to current ratio.
        if (_filledTex != null && _filledRatio > 0f)
        {
            var fillW = totalPxW * _filledRatio;
            var destFill = UIBox2.FromDimensions(new Vector2(0, barOffsetY), new Vector2(fillW, barPxH));
            var srcFillW = _filledTex.Width * _filledRatio;
            var srcFill = UIBox2.FromDimensions(Vector2.Zero, new Vector2(srcFillW, _filledTex.Height));
            handle.DrawTextureRectRegion(_filledTex, destFill, srcFill);
        }
    }
}
