using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CECurrencyUI : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    private const string RsiPath = "/Textures/_CE/Interface/coins.rsi";

    private readonly BoxContainer _gpGroup;
    private readonly BoxContainer _spGroup;
    private readonly BoxContainer _cpGroup;
    private readonly Label _gpLabel;
    private readonly Label _spLabel;
    private readonly Label _cpLabel;

    public CECurrencyUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var font = new VectorFont(
            _resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        var rsi = _resCache.GetResource<RSIResource>(RsiPath).RSI;

        (_gpGroup, _gpLabel) = CreateDenomination(rsi["g"].Frame0, font);
        (_spGroup, _spLabel) = CreateDenomination(rsi["s"].Frame0, font);
        (_cpGroup, _cpLabel) = CreateDenomination(rsi["c"].Frame0, font);

        Container.AddChild(_gpGroup);
        Container.AddChild(_spGroup);
        Container.AddChild(_cpGroup);

        SetCoins(0);
    }

    private static (BoxContainer group, Label label) CreateDenomination(Texture icon, VectorFont font)
    {
        var group = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
        };

        var tex = new TextureRect
        {
            Texture = icon,
            MinSize = new Vector2(16, 16),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            VerticalAlignment = VAlignment.Center,
        };

        var label = new Label
        {
            FontOverride = font,
            FontColorOverride = Color.White,
            VerticalAlignment = VAlignment.Center,
        };

        group.AddChild(tex);
        group.AddChild(label);
        return (group, label);
    }

    public void SetCoins(int total)
    {
        var remaining = total;
        var gp = remaining / 100;
        remaining %= 100;
        var sp = remaining / 10;
        remaining %= 10;
        var cp = remaining;

        _gpGroup.Visible = gp > 0;
        _spGroup.Visible = sp > 0;
        _cpGroup.Visible = cp > 0;

        _gpLabel.Text = gp.ToString();
        _spLabel.Text = sp.ToString();
        _cpLabel.Text = cp.ToString();
    }
}
