using System.Numerics;
using Content.Shared._CE.Health.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEHealthUI : UIWidget
{
    [Dependency] private readonly IResourceCache _resCache = default!;

    private CEMobState _lastMobState = (CEMobState) 255; // invalid sentinel
    private int _lastHealthState = -1;

    private const string AliveRsiPath = "/Textures/_CE/Interface/HealthMana/alive.rsi";
    private const string CriticalRsiPath = "/Textures/_CE/Interface/HealthMana/critical.rsi";
    private const string DeadRsiPath = "/Textures/_CE/Interface/HealthMana/dead.rsi";

    private const int MaxHealthStates = 10; // health0..health9
    private const float TextureScale = 3f;

    public CEHealthUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HealthTexture.DisplayRect.TextureScale = new Vector2(TextureScale, TextureScale);

        var vollkornFont = new VectorFont(_resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        HealthLabel.FontOverride = vollkornFont;
    }

    public void UpdateHealthDisplay(CEDamageableComponent damageable, CEMobStateComponent mobState)
    {
        var currentState = mobState.CurrentState;
        var critThreshold = mobState.CriticalThreshold;
        var currentHp = Math.Max(0, critThreshold - damageable.TotalDamage);

        float ratio;

        switch (currentState)
        {
            case CEMobState.Alive:
            {
                ratio = critThreshold > 0
                    ? Math.Clamp((float) currentHp / critThreshold, 0f, 1f)
                    : 0f;
                break;
            }
            case CEMobState.Critical:
            {
                ratio = 0f;
                break;
            }
            default: // Dead
            {
                ratio = 0f;
                break;
            }
        }

        HealthLabel.Text = $"{currentHp}/{critThreshold}";

        if (currentState != _lastMobState)
        {
            _lastMobState = currentState;
            _lastHealthState = -1;
        }

        switch (currentState)
        {
            case CEMobState.Alive:
            {
                var stateIndex = (int) (ratio * (MaxHealthStates - 1));
                stateIndex = Math.Clamp(stateIndex, 0, MaxHealthStates - 1);

                if (stateIndex != _lastHealthState)
                {
                    _lastHealthState = stateIndex;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(AliveRsiPath),
                        $"health{stateIndex}");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
            case CEMobState.Critical:
            {
                if (_lastHealthState != -2)
                {
                    _lastHealthState = -2;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(CriticalRsiPath),
                        "critical");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
            default:
            {
                if (_lastHealthState != -3)
                {
                    _lastHealthState = -3;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(DeadRsiPath),
                        "dead");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
        }
    }
}
