using System.Numerics;
using Content.Shared._CE.Health;
using Content.Shared._CE.Health.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEHealthUI : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    private bool _lastMobCriticalState;
    private int _lastHealthState = -1;

    private const string AliveRsiPath = "/Textures/_CE/Interface/HealthMana/alive.rsi";
    private const string CriticalRsiPath = "/Textures/_CE/Interface/HealthMana/critical.rsi";

    private const int MaxHealthStates = 10; // health0..health9
    private const float TextureScale = 3f;

    public CEHealthUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HealthTexture.DisplayRect.TextureScale = new Vector2(TextureScale, TextureScale);

        var vollkornFont = new VectorFont(_resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        HealthLabel.FontOverride = vollkornFont;
    }

    public void UpdateHealthDisplay(CEHealthInfo info)
    {
        var critical = info.HasMobState && info.Critical;
        var ratio = !critical ? info.Ratio : 0f;

        HealthLabel.Text = critical switch
        {
            true when info.DestroyThreshold != null =>
                $"{info.RemainingUntilDeath}/{info.DestroyThreshold}",
            _ => $"{info.CurrentHp}/{info.MaxHp}",
        };

        if (critical != _lastMobCriticalState)
        {
            _lastMobCriticalState = critical;
            _lastHealthState = -1;
        }

        switch (critical)
        {
            case false:
            {
                var stateIndex = (int) (ratio * (MaxHealthStates - 1));
                stateIndex = Math.Clamp(stateIndex, 0, MaxHealthStates - 1);

                if (stateIndex != _lastHealthState)
                {
                    _lastHealthState = stateIndex;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(AliveRsiPath),
                        $"health{stateIndex}");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
            case true:
            {
                if (_lastHealthState != -2)
                {
                    _lastHealthState = -2;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(CriticalRsiPath),
                        "critical");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
        }
    }
}
