using System.Numerics;
using Content.Shared.Damage.Components;
using Content.Shared.FixedPoint;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Mobs.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEHealthUI : UIWidget
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    private MobThresholdSystem? _mobThreshold;

    private MobState _lastMobState = MobState.Invalid;
    private int _lastHealthState = -1;

    private const string AliveRsiPath = "/Textures/_CE/Interface/HealthMana/alive.rsi";
    private const string CriticalRsiPath = "/Textures/_CE/Interface/HealthMana/critical.rsi";
    private const string DeadRsiPath = "/Textures/_CE/Interface/HealthMana/dead.rsi";

    private const int MaxHealthStates = 10; // health0..health9
    private const float TextureScale = 3f;

    public CEHealthUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HealthTexture.DisplayRect.TextureScale = new Vector2(TextureScale, TextureScale);

        // Set Vollkorn font
        var vollkornFont = new VectorFont(_resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        HealthLabel.FontOverride = vollkornFont;
    }

    public void UpdateHealthDisplay(
        EntityUid uid,
        MobStateComponent mobState,
        DamageableComponent dmg,
        MobThresholdsComponent thresholds)
    {
        _mobThreshold ??= _entManager.System<MobThresholdSystem>();

        var currentState = mobState.CurrentState;

        if (_mobThreshold is null)
            return;

        FixedPoint2 maxHp;
        FixedPoint2 currentHp;
        float ratio;

        switch (currentState)
        {
            case MobState.Alive:
            {
                if (!_mobThreshold.TryGetThresholdForState(uid, MobState.Critical, out var threshold, thresholds) &&
                    !_mobThreshold.TryGetThresholdForState(uid, MobState.Dead, out threshold, thresholds))
                {
                    threshold = FixedPoint2.New(1);
                }

                maxHp = threshold.Value;
                currentHp = FixedPoint2.Max(maxHp - dmg.TotalDamage, FixedPoint2.Zero);
                ratio = 1f - (dmg.TotalDamage / threshold.Value).Float();
                ratio = Math.Clamp(ratio, 0f, 1f);
                break;
            }
            case MobState.Critical:
            {
                if (!_mobThreshold.TryGetThresholdForState(uid, MobState.Critical, out var critThreshold, thresholds))
                    critThreshold = FixedPoint2.Zero;

                if (!_mobThreshold.TryGetThresholdForState(uid, MobState.Dead, out var deadThreshold, thresholds))
                    deadThreshold = critThreshold;

                var maxToDead = deadThreshold.Value;
                var remainingToDead = FixedPoint2.Max(maxToDead - dmg.TotalDamage, FixedPoint2.Zero);

                maxHp = maxToDead;
                currentHp = remainingToDead;
                ratio = 0f;
                break;
            }
            default:
            {
                if (!_mobThreshold.TryGetThresholdForState(uid, MobState.Critical, out var critThreshold, thresholds))
                {
                    _mobThreshold.TryGetThresholdForState(uid, MobState.Dead, out critThreshold, thresholds);
                    critThreshold ??= FixedPoint2.New(1);
                }

                maxHp = critThreshold.Value;
                currentHp = FixedPoint2.Zero;
                ratio = 0f;
                break;
            }
        }

        HealthLabel.Text = currentState == MobState.Critical
            ? $"-{currentHp.Int()}/-{maxHp.Int()}"
            : $"{currentHp.Int()}/{maxHp.Int()}";

        if (currentState != _lastMobState)
        {
            _lastMobState = currentState;
            _lastHealthState = -1;
        }

        switch (currentState)
        {
            case MobState.Alive:
            {
                var stateIndex = (int) (ratio * (MaxHealthStates - 1));
                stateIndex = Math.Clamp(stateIndex, 0, MaxHealthStates - 1);

                if (stateIndex != _lastHealthState)
                {
                    _lastHealthState = stateIndex;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(AliveRsiPath), $"health{stateIndex}");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
            case MobState.Critical:
            {
                if (_lastHealthState != -2)
                {
                    _lastHealthState = -2;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(CriticalRsiPath), "critical");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
            default:
            {
                if (_lastHealthState != -3)
                {
                    _lastHealthState = -3;
                    var specifier = new SpriteSpecifier.Rsi(
                        new ResPath(DeadRsiPath), "dead");
                    HealthTexture.SetFromSpriteSpecifier(specifier);
                }

                break;
            }
        }
    }
}
