using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEManaUI : UIWidget
{
    [Dependency] private readonly IResourceCache _resCache = default!;

    private int _lastManaState = -1;

    private const string ManaRsiPath = "/Textures/_CE/Interface/HealthMana/mana.rsi";
    private const int MaxManaStates = 11; // mana0..mana10
    private const float TextureScale = 3f;

    public CEManaUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ManaTexture.DisplayRect.TextureScale = new Vector2(TextureScale, TextureScale);

        // Set Vollkorn font
        var vollkornFont = new VectorFont(_resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        ManaLabel.FontOverride = vollkornFont;

        // Initialize mana at 0.5
        SetMana(0.5f, 5, 10);
    }
    /// <summary>
    ///     Public method to update mana from an external system in the future.
    /// </summary>
    public void SetMana(float ratio, int current, int max)
    {
        ratio = Math.Clamp(ratio, 0f, 1f);

        var stateIndex = (int) (ratio * (MaxManaStates - 1));
        stateIndex = Math.Clamp(stateIndex, 0, MaxManaStates - 1);

        if (stateIndex != _lastManaState)
        {
            _lastManaState = stateIndex;
            var specifier = new SpriteSpecifier.Rsi(
                new ResPath(ManaRsiPath), $"mana{stateIndex}");
            ManaTexture.SetFromSpriteSpecifier(specifier);
        }

        ManaLabel.Text = $"{current}/{max}";
    }
}
