using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CESoulUI : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    private const string SoulIconRsiPath = "/Textures/_CE/Effects/soul.rsi";
    private const string SoulIconState = "effect";

    public CESoulUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var vollkornFont = new VectorFont(
            _resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 14);
        SoulLabel.FontOverride = vollkornFont;

        SoulIcon.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(new ResPath(SoulIconRsiPath), SoulIconState));

        SetSouls(0);
    }

    /// <summary>
    /// Updates the displayed soul count.
    /// </summary>
    public void SetSouls(int current)
    {
        SoulLabel.Text = current.ToString();
    }
}
