using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.HealthMana.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEStaminaUI : UIWidget
{
    private const string StaminaRsiPath = "/Textures/_CE/Interface/HealthMana/stamina.rsi";
    private const float TextureScale = 3f;

    [Dependency] private readonly IResourceCache _resCache = default!;

    private Texture? _emptyTex;
    private Texture? _filledTex;
    private Texture? _exhaustedTex;

    private float _ratio = 1f;
    private bool _exhausted;

    public CEStaminaUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadTextures();

        if (_emptyTex != null)
        {
            var w = _emptyTex.Width * TextureScale;
            var h = _emptyTex.Height * TextureScale;
            MinWidth = w;
            MinHeight = h;
            SetWidth = w;
            SetHeight = h;
        }

        var font = new VectorFont(
            _resCache.GetResource<FontResource>("/Fonts/_CE/Vollkorn/VollkornSC-Regular.ttf"), 12);
        StaminaLabel.FontOverride = font;
        StaminaLabel.FontColorOverride = Color.White;
    }

    private void LoadTextures()
    {
        if (!_resCache.TryGetResource<RSIResource>(new ResPath(StaminaRsiPath), out var rsi))
            return;

        if (rsi.RSI.TryGetState("empty", out var emptyState))
            _emptyTex = emptyState.Frame0;

        if (rsi.RSI.TryGetState("filled", out var filledState))
            _filledTex = filledState.Frame0;

        if (rsi.RSI.TryGetState("exhausted", out var exhaustedState))
            _exhaustedTex = exhaustedState.Frame0;
    }

    public void SetStamina(float ratio, int current, int max, bool exhausted)
    {
        _ratio = Math.Clamp(ratio, 0f, 1f);
        _exhausted = exhausted;

        StaminaLabel.Text = $"{current}/{max}";
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var size = PixelSize;
        var destRect = UIBox2.FromDimensions(Vector2.Zero, size);

        // Always draw the empty background.
        if (_emptyTex != null)
            handle.DrawTextureRect(_emptyTex, destRect);

        // Draw fill bar clipped to ratio.
        var fillTex = _exhausted ? _exhaustedTex : _filledTex;

        if (fillTex != null && _ratio > 0f)
        {
            var fillWidth = size.X * _ratio;
            var destFill = UIBox2.FromDimensions(Vector2.Zero, new Vector2(fillWidth, size.Y));

            // Sub-region of the source texture (in pixel coordinates).
            var srcWidth = fillTex.Width * _ratio;
            var srcRegion = UIBox2.FromDimensions(Vector2.Zero, new Vector2(srcWidth, fillTex.Height));

            handle.DrawTextureRectRegion(fillTex, destFill, srcRegion);
        }
    }
}
