- type: entity
  abstract: true
  id: CEBaseWeaponTwoHandedSword
  categories: [ ForkFiltered ]
  parent:
  - BaseItem
  components:
  - type: Item
    size: Ginormous
  - type: CEItemAnimation
    spriteRotation: -90
    animationSpeed: 0.5 #Slow attacks
    animations:
      Primary:
      - SwordAttackLight1
      - SwordAttackLight2
      Secondary:
      - SwordAttackLight1
      - SwordAttackLight2
  - type: CEWieldedItemAnimation
    animations:
      Primary:
      - SwordAttackHeavy1 #TODO: IDK why but combos from Wielded doesnt work. Something related to combo deadline i think. Fix that later. Meow
      - SwordAttackHeavy2
      Secondary:
      - SwordAttackHeavy1
      - SwordAttackHeavy2
  - type: Clothing
    slots:
    - neck
    equipWhileMoving: true
    equipDelay: 1
    unequipDelay: 1
  - type: Wieldable
  - type: CEMeleeWeapon
    rangeMultiplier: 1.2 #Longer reach
    damage:
      types:
        Slash: 4 #Higher damage