- type: entity
  abstract: true
  id: CEBaseWeaponTwoHandedSword
  categories: [ ForkFiltered ]
  parent:
  - BaseItem
  components:
  - type: Item
    size: Ginormous
  - type: CEWeapon
    spriteRotation: -90
    animations:
      Primary:
      - anim: SwordAttackLight1
        speed: 0.5
      - anim: SwordAttackLight2
        speed: 0.5
      Secondary:
      - anim: SwordAttackLight1
        speed: 0.5
      - anim: SwordAttackLight2
        speed: 0.5
  - type: CEWieldedWeapon
    animations:
      Primary:
      - anim: SwordAttackHeavy1
        speed: 0.5
      - anim: SwordAttackHeavy2
        speed: 0.5
      Secondary:
      - anim: SwordAttackHeavy1
        speed: 0.5
      - anim: SwordAttackHeavy2
        speed: 0.5
  - type: Clothing
    slots:
    - neck
    equipWhileMoving: true
    equipDelay: 1
    unequipDelay: 1
  - type: Wieldable
  - type: CEMeleeWeapon
    rangeMultiplier: 1.2 #Longer reach
    damageGroups:
      default:
        damage:
          Physical: 4
      pierce:
        damage:
          Physical: 4
