- type: entity
  abstract: true
  id: CEBaseWeaponSpear
  categories: [ ForkFiltered ]
  parent: [ BaseItem ]
  components:
  - type: Item
    size: Ginormous
  - type: CEWeapon
    spriteRotation: -90
    effectSlots:
      OnHit:
      - !type:WeaponArcAttack
        range: 1.26
        arcWidth: 15
        effects:
        - !type:Damage
          damage:
            types:
              Physical: 2
      OnHeavyHit:
      - !type:WeaponArcAttack
        range: 1.4
        arcWidth: 25
        effects:
        - !type:Damage
          damage:
            types:
              Physical: 4
    animations:
      Primary:
      - anim: SpearAttackLight
        staminaCost: 2
      Secondary:
      - anim: SpearAttackHeavy
        staminaCost: 3
      - anim: SpearAttackHeavy2
        staminaCost: 3
  #- type: CEWieldedWeapon #TODO: Custom wielded animations
  #  animations:
  #    Primary:
  #    - anim: SpearAttackLight
  #    Secondary:
  #    - anim: SpearAttackHeavy
  - type: Wieldable
  - type: Clothing
    slots: [ neck ]
    equipWhileMoving: true
    equipDelay: 1
    unequipDelay: 1
