using System.Numerics;
using Content.Shared._CE.Minimap;
using Content.Shared._CE.Procedural;
using Content.Shared._CE.ZLevels.Core.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.Minimap.Widgets;

/// <summary>
/// Minimap widget that draws the procedurally-generated dungeon graph (rooms + connections)
/// around the local player, plus an arrow indicating the player's position and facing.
///
/// The widget is fully self-driven: every frame it locates the local player, looks up the
/// dungeon graph either on the player's current map or on a sibling map of the same z-level
/// network, and renders nothing if either piece of data is missing.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEMinimapUI : UIWidget
{
    private const float WidgetSize = 220f;
    private const float DefaultTilePixelSize = 4f; // world tile -> minimap pixels at scale 1
    private const float MinTilePixelSize = 1.5f;
    private const float MaxTilePixelSize = 12f;
    private const float ZoomStep = 1.25f; // multiplicative per wheel notch

    /// <summary>
    /// Per-instance zoom: how many minimap pixels (at UI scale 1) one world tile occupies.
    /// Adjusted by the mouse wheel while the cursor is over the widget.
    /// </summary>
    private float _tilePixelSize = DefaultTilePixelSize;

    /// <summary>
    /// Reused each frame to track rooms that are adjacent to a visited room but not yet visited.
    /// Cleared at the start of every Draw() call to avoid per-frame allocations.
    /// </summary>
    private readonly HashSet<int> _previewRooms = new();

    private static readonly Color BackgroundColor = new(0f, 0f, 0f, 0.35f);
    private static readonly Color FrameColor = Color.White.WithAlpha(0.4f);
    private static readonly Color RoomPreviewColor = Color.White.WithAlpha(0.10f);
    private static readonly Color RoomVisitedColor = Color.White.WithAlpha(0.32f);
    private static readonly Color RoomCurrentColor = Color.White.WithAlpha(0.55f);
    private static readonly Color ConnectionPreviewColor = Color.White.WithAlpha(0.18f);
    private static readonly Color ConnectionVisitedColor = Color.White.WithAlpha(0.45f);
    private static readonly Color ArrowColor = Color.Red;
    private static readonly Color IconPreviewColor = Color.White.WithAlpha(0.45f);
    private static readonly Color IconVisitedColor = Color.White;

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly Dictionary<ProtoId<CERoomTypePrototype>, Texture?> _iconCache = new();

    public CEMinimapUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MinSize = new Vector2(WidgetSize, WidgetSize);
        SetSize = new Vector2(WidgetSize, WidgetSize);
        MouseFilter = MouseFilterMode.Stop;

        BuildIconCache();
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (args.Delta.Y == 0f)
            return;

        var factor = args.Delta.Y > 0 ? ZoomStep : 1f / ZoomStep;
        _tilePixelSize = Math.Clamp(_tilePixelSize * factor, MinTilePixelSize, MaxTilePixelSize);
        args.Handle();
    }

    private void BuildIconCache()
    {
        foreach (var proto in _proto.EnumeratePrototypes<CERoomTypePrototype>())
        {
            _iconCache[proto.ID] = ResolveIcon(proto.MinimapIcon);
        }
    }

    private Texture? ResolveIcon(SpriteSpecifier? sprite)
    {
        if (sprite is SpriteSpecifier.Rsi rsi &&
            _resCache.TryGetResource<RSIResource>(rsi.RsiPath, out var rsiRes) &&
            rsiRes.RSI.TryGetState(rsi.RsiState, out var state))
            return state.Frame0;
        return null;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_player.LocalEntity is not { } player)
            return;

        if (!_entMan.TryGetComponent<CEMinimapDataComponent>(player, out var minimap))
            return;

        if (!_entMan.TryGetComponent<TransformComponent>(player, out var xform))
            return;

        if (!TryFindDungeon(xform, out var dungeon) || dungeon.Rooms.Count == 0)
            return;

        var size = Size;
        var scale = UIScale;

        var widgetRect = UIBox2.FromDimensions(Vector2.Zero, size * scale);
        handle.DrawRect(widgetRect, BackgroundColor);
        DrawRectOutline(handle, widgetRect, FrameColor);

        var center = (size * scale) / 2f;

        // World tile coords of the player.
        var playerWorld = _entMan.System<SharedTransformSystem>().GetWorldPosition(xform);

        var pixelsPerTile = _tilePixelSize * scale;

        // Build a "preview" set: rooms not visited, but directly connected to a visited one.
        // All preview rooms are rendered as faint rectangles; their type-icons are hidden
        // (revealed only on actual entry) — with the exception of treasure rooms, whose icon
        // is intentionally peeked-through so the player can spot them from a neighbour.
        var visited = minimap.VisitedRooms;
        _previewRooms.Clear();
        foreach (var conn in dungeon.Connections)
        {
            if (visited.Contains(conn.RoomA) && !visited.Contains(conn.RoomB))
            {
                if (conn.RoomB >= 0 && conn.RoomB < dungeon.Rooms.Count)
                {
                    var candidate = dungeon.Rooms[conn.RoomB];
                    if (candidate.RoomType == null || !_proto.TryIndex(candidate.RoomType.Value, out CERoomTypePrototype? rtB) || !rtB.SecretRoom)
                        _previewRooms.Add(conn.RoomB);
                }
            }
            else if (visited.Contains(conn.RoomB) && !visited.Contains(conn.RoomA))
            {
                if (conn.RoomA >= 0 && conn.RoomA < dungeon.Rooms.Count)
                {
                    var candidate = dungeon.Rooms[conn.RoomA];
                    if (candidate.RoomType == null || !_proto.TryIndex(candidate.RoomType.Value, out CERoomTypePrototype? rtA) || !rtA.SecretRoom)
                        _previewRooms.Add(conn.RoomA);
                }
            }
        }

        bool IsRoomVisible(int idx) => visited.Contains(idx) || _previewRooms.Contains(idx);

        // Connections (lines between centers of connected rooms). Only draw between visible rooms.
        foreach (var conn in dungeon.Connections)
        {
            if (conn.RoomA < 0 || conn.RoomA >= dungeon.Rooms.Count
                               || conn.RoomB < 0 || conn.RoomB >= dungeon.Rooms.Count)
                continue;

            if (!IsRoomVisible(conn.RoomA) || !IsRoomVisible(conn.RoomB))
                continue;

            var a = dungeon.Rooms[conn.RoomA];
            var b = dungeon.Rooms[conn.RoomB];

            var aCenter = a.Position + (Vector2)a.Size / 2f;
            var bCenter = b.Position + (Vector2)b.Size / 2f;

            var aPx = WorldTileToWidget(aCenter, playerWorld, center, pixelsPerTile);
            var bPx = WorldTileToWidget(bCenter, playerWorld, center, pixelsPerTile);

            // Clip the segment to the widget rect so connection lines never spill outside.
            if (!ClipLineToRect(ref aPx, ref bPx, widgetRect))
                continue;

            var bothVisited = visited.Contains(conn.RoomA) && visited.Contains(conn.RoomB);
            handle.DrawLine(aPx, bPx, bothVisited ? ConnectionVisitedColor : ConnectionPreviewColor);
        }

        // Rooms.
        foreach (var room in dungeon.Rooms)
        {
            if (!IsRoomVisible(room.Index))
                continue;

            var minTile = (Vector2)room.Position;
            var maxTile = minTile + room.Size;

            var minPx = WorldTileToWidget(minTile, playerWorld, center, pixelsPerTile);
            var maxPx = WorldTileToWidget(maxTile, playerWorld, center, pixelsPerTile);

            var roomBox = new UIBox2(MathF.Min(minPx.X, maxPx.X),
                MathF.Min(minPx.Y, maxPx.Y),
                MathF.Max(minPx.X, maxPx.X),
                MathF.Max(minPx.Y, maxPx.Y));

            // Cull rooms entirely outside the widget area.
            if (roomBox.Right < widgetRect.Left || roomBox.Left > widgetRect.Right
                                                || roomBox.Bottom < widgetRect.Top || roomBox.Top > widgetRect.Bottom)
                continue;

            var isVisited = visited.Contains(room.Index);

            Color color;
            if (minimap.CurrentRoom == room.Index)
                color = RoomCurrentColor;
            else if (isVisited)
                color = RoomVisitedColor;
            else
                color = RoomPreviewColor;

            var clipped = ClipToRect(roomBox, widgetRect);
            if (clipped.HasValue)
                handle.DrawRect(clipped.Value, color);

            // Type icon overlay (drawn on top of the room rect).
            // Visible in visited rooms; in preview state shown only for room types that have
            // ShowIconFromNeighbour = true (e.g. treasure rooms).
            var roomTypeProto = room.RoomType != null && _proto.Resolve(room.RoomType.Value, out var roomType)
                ? roomType
                : null;
            var showIcon = isVisited || (_previewRooms.Contains(room.Index) && roomTypeProto?.ShowIconFromNeighbour == true);
            var icon = showIcon && roomTypeProto != null ? _iconCache.GetValueOrDefault(roomTypeProto.ID) : null;

            if (icon == null || !clipped.HasValue)
                continue;

            var iconColor = isVisited ? IconVisitedColor : IconPreviewColor;
            var iconCenter = new Vector2((roomBox.Left + roomBox.Right) / 2f,
                (roomBox.Top + roomBox.Bottom) / 2f);

            // Only render the icon when its center lies inside the widget rect — otherwise
            // a partially-visible room would still spill its icon outside the minimap.
            if (iconCenter.X >= widgetRect.Left &&
                iconCenter.X <= widgetRect.Right &&
                iconCenter.Y >= widgetRect.Top &&
                iconCenter.Y <= widgetRect.Bottom)
            {
                // Scale icon: roughly 2x the previous size — cap to room size and to ~32 px at scale=1.
                var maxIconPx = MathF.Min(roomBox.Width, roomBox.Height) * 1.7f;
                var nativeSize = MathF.Max(icon.Width, icon.Height);
                var iconScale = MathF.Min(maxIconPx / nativeSize, 32f * scale / nativeSize);
                var iconHalf = new Vector2(icon.Width, icon.Height) * iconScale * 0.5f;

                var iconQuad = new UIBox2(iconCenter - iconHalf, iconCenter + iconHalf);
                handle.DrawTextureRect(icon, iconQuad, iconColor);
            }
        }

        // Player arrow on top.
        DrawPlayerArrow(handle, center, xform.LocalRotation.Theta, scale);
    }

    /// <summary>
    /// Locates dungeon data either on the player's current map or, failing that, on any
    /// map in the same z-level network.
    /// </summary>
    private bool TryFindDungeon(TransformComponent xform, out CEGeneratingProceduralDungeonComponent dungeon)
    {
        dungeon = null!;

        if (xform.MapUid is not { } currentMap)
            return false;

        if (_entMan.TryGetComponent(currentMap, out CEGeneratingProceduralDungeonComponent? direct))
        {
            dungeon = direct;
            return true;
        }

        var zLevels = _entMan.System<CESharedZLevelsSystem>();
        if (!zLevels.TryGetZNetwork(currentMap, out var zNet))
            return false;

        foreach (var sibling in zNet.Comp.ZLevels.Values)
        {
            if (sibling is { } siblingUid
                && _entMan.TryGetComponent(siblingUid, out CEGeneratingProceduralDungeonComponent? found))
            {
                dungeon = found;
                return true;
            }
        }

        return false;
    }

    private static Vector2 WorldTileToWidget(Vector2 worldTile,
        Vector2 playerWorldTile,
        Vector2 widgetCenter,
        float pixelsPerTile)
    {
        var delta = worldTile - playerWorldTile;
        // Y is flipped: world +Y is up, screen +Y is down.
        return widgetCenter + new Vector2(delta.X * pixelsPerTile, -delta.Y * pixelsPerTile);
    }

    private static UIBox2? ClipToRect(UIBox2 box, UIBox2 clip)
    {
        var left = MathF.Max(box.Left, clip.Left);
        var top = MathF.Max(box.Top, clip.Top);
        var right = MathF.Min(box.Right, clip.Right);
        var bottom = MathF.Min(box.Bottom, clip.Bottom);
        if (right <= left || bottom <= top)
            return null;
        return new UIBox2(left, top, right, bottom);
    }

    /// <summary>
    /// Liang–Barsky line clipping. Mutates <paramref name="a"/> and <paramref name="b"/> to the
    /// segment that lies inside <paramref name="rect"/>. Returns false if the segment is fully outside.
    /// </summary>
    private static bool ClipLineToRect(ref Vector2 a, ref Vector2 b, UIBox2 rect)
    {
        var dx = b.X - a.X;
        var dy = b.Y - a.Y;
        float t0 = 0f, t1 = 1f;

        if (!ClipT(-dx, a.X - rect.Left, ref t0, ref t1))
            return false;
        if (!ClipT(dx, rect.Right - a.X, ref t0, ref t1))
            return false;
        if (!ClipT(-dy, a.Y - rect.Top, ref t0, ref t1))
            return false;
        if (!ClipT(dy, rect.Bottom - a.Y, ref t0, ref t1))
            return false;

        var newA = new Vector2(a.X + t0 * dx, a.Y + t0 * dy);
        var newB = new Vector2(a.X + t1 * dx, a.Y + t1 * dy);
        a = newA;
        b = newB;
        return true;
    }

    private static bool ClipT(float p, float q, ref float t0, ref float t1)
    {
        if (p == 0f)
            return q >= 0f;

        var t = q / p;
        if (p < 0f)
        {
            if (t > t1)
                return false;
            if (t > t0)
                t0 = t;
        }
        else
        {
            if (t < t0)
                return false;
            if (t < t1)
                t1 = t;
        }

        return true;
    }

    private static void DrawRectOutline(DrawingHandleScreen handle, UIBox2 box, Color color)
    {
        handle.DrawLine(new Vector2(box.Left, box.Top), new Vector2(box.Right, box.Top), color);
        handle.DrawLine(new Vector2(box.Right, box.Top), new Vector2(box.Right, box.Bottom), color);
        handle.DrawLine(new Vector2(box.Right, box.Bottom), new Vector2(box.Left, box.Bottom), color);
        handle.DrawLine(new Vector2(box.Left, box.Bottom), new Vector2(box.Left, box.Top), color);
    }

    /// <summary>
    /// Draws an outlined white triangle pointing in the player's facing direction.
    /// The entity rotation is the angle east-of-north (south is 0); we rotate the canonical
    /// up-pointing arrow by that angle to match the world facing on the minimap.
    /// </summary>
    private static void DrawPlayerArrow(DrawingHandleScreen handle, Vector2 center, double rotationRadians, float scale)
    {
        var size = 8f * scale;
        // Local-space arrow pointing up (toward -Y in screen space).
        var tip = new Vector2(0f, -size);
        var left = new Vector2(-size * 0.7f, size * 0.6f);
        var right = new Vector2(size * 0.7f, size * 0.6f);

        // Negative rotation because screen Y is flipped vs world Y, plus 180° to invert direction.
        var rot = -(float)rotationRadians + MathF.PI;
        var cos = MathF.Cos(rot);
        var sin = MathF.Sin(rot);

        Vector2 Rotate(Vector2 v) => new(v.X * cos - v.Y * sin, v.X * sin + v.Y * cos);

        var p1 = center + Rotate(tip);
        var p2 = center + Rotate(left);
        var p3 = center + Rotate(right);

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList,
            new[] { p1, p2, p3 },
            ArrowColor);
    }
}
