- type: entity
  abstract: true
  id: CEBaseWeaponThrowable
  categories: [ HideSpawnMenu, ForkFiltered ]
  components:
  - type: LandAtCursor
  - type: DamageOtherOnHit
    damage:
      types:
        Piercing: 10
  - type: DamageOnLand
    damage:
      types:
        Piercing: 10
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PolygonShape
          vertices:
            - -0.40,-0.30
            - -0.30,-0.40
            - 0.40,0.30
            - 0.30,0.40
        density: 10
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2

#- type: entity
#  abstract: true
#  id: CEBaseWeaponSharp
#  categories: [ HideSpawnMenu, ForkFiltered ]
#  components:
#  - type: Sharp
#  - type: CESharpened
#  - type: CESharpeningStone
#  - type: UseDelay
#  - type: Tool
#    qualities:
#      - Slicing
#    useSound:
#      path: /Audio/Items/Culinary/chop.ogg
#  - type: Utensil
#    types:
#      - Knife
#  - type: CEWallpaperRemover
#  - type: Execution
#
#- type: entity
#  abstract: true
#  id: CEBaseWeaponDestructible
#  categories: [ HideSpawnMenu, ForkFiltered ]
#  components:
#  - type: ExaminableDamage
#    messages: CEWeaponMessages
#  - type: Damageable
#    damageContainer: Inorganic
#  - type: CEMeleeParriable
#  - type: Destructible
#    thresholds:
#    - trigger:
#        !type:DamageTrigger
#        damage: 80
#      behaviors:
#      - !type:PlaySoundBehavior
#        sound:
#          collection: MetalBreak
#      - !type:DoActsBehavior
#        acts: ["Destruction"]

#- type: entity
#  abstract: true
#  id: CEBaseWeaponSelfDamage
#  categories: [ HideSpawnMenu, ForkFiltered ]
#  components:
#  - type: CEMeleeSelfDamage
#    damageToSelf:
#      types:
#        Blunt: 0.5 # 100 hits

- type: entity
  abstract: true
  id: CEBaseWeaponExecution
  categories: [ HideSpawnMenu, ForkFiltered ]
  components:
  - type: Execution
    internalMeleeExecutionMessage: "ce-execution-popup-melee-initial-internal"
    externalMeleeExecutionMessage: "ce-execution-popup-melee-initial-external"
    completeInternalMeleeExecutionMessage: "ce-execution-popup-melee-complete-internal"
    completeExternalMeleeExecutionMessage: "ce-execution-popup-melee-complete-external"
    internalSelfExecutionMessage: "ce-execution-popup-self-initial-internal"
    externalSelfExecutionMessage: "ce-execution-popup-self-initial-external"
    completeInternalSelfExecutionMessage: "ce-execution-popup-self-complete-internal"
    completeExternalSelfExecutionMessage: "ce-execution-popup-self-complete-external"
