using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : DefaultWindow
{
    [Dependency] private readonly ISharedAdminManager _adminManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public ObserveWarningWindow()
    {
        Title = Loc.GetString("observe-warning-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var player = _playerManager.LocalSession;

        // CrystallEdge: upstream player-observe confirmation is suppressed; the popup only keeps the admin observer action.
        ObserveButton.Visible = false;

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }
        else
        {
            ObserveAsAdminButton.Visible = false;
        }

        NevermindButton.OnPressed += _ => { this.Close(); };
    }
}
