- type: entity
  abstract: true
  id: CEBaseWeaponSkimitar
  categories: [ ForkFiltered ]
  parent:
  - BaseItem
  components:
  - type: Item
    size: Ginormous
  - type: CEWeapon
    spriteRotation: -90
    damage:
      types:
        Physical: 2
    animations:
      Primary:
      - anim: SkimitarAttackLight1
      - anim: SkimitarAttackLight2
      Secondary:
      - anim: SkimitarAttackHeavy1
  - type: Clothing
    slots:
    - neck
    equipWhileMoving: true
    equipDelay: 1
    unequipDelay: 1
