using Content.Client._CE.Procedural.Overview;
using Content.Shared._CE.Procedural.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Procedural.Admin;

[GenerateTypedNameReferences]
public sealed partial class CEAdminDungeonOverviewWindow : DefaultWindow
{
    public event Action<NetEntity>? OnTeleportRequested;

    public CEAdminDungeonOverviewWindow()
    {
        RobustXamlLoader.Load(this);

        OverviewControl.EnableTeleport = true;
        OverviewControl.DetailsHeaderLocId = "ce-admin-dungeon-overview-instances-header";
        OverviewControl.GraphHeaderLocId = "ce-admin-dungeon-overview-graph-header";
        OverviewControl.OnTeleportRequested += target => OnTeleportRequested?.Invoke(target);
    }

    public void UpdateState(CEAdminDungeonOverviewState state)
    {
        var levels = new List<CEDungeonOverviewLevelView>(state.Levels.Count);
        foreach (var level in state.Levels)
        {
            var instances = new List<CEDungeonOverviewInstanceView>(level.Instances.Count);
            foreach (var inst in level.Instances)
            {
                var players = new List<CEDungeonOverviewPlayerView>(inst.Players.Count);
                foreach (var p in inst.Players)
                {
                    players.Add(new CEDungeonOverviewPlayerView
                    {
                        Entity = p.Entity,
                        CharacterName = p.CharacterName,
                        AccountName = p.AccountName,
                    });
                }

                instances.Add(new CEDungeonOverviewInstanceView
                {
                    PlayerCount = inst.Players.Count,
                    Players = players,
                });
            }

            var totalPlayers = 0;
            foreach (var inst in instances)
                totalPlayers += inst.PlayerCount;

            levels.Add(new CEDungeonOverviewLevelView
            {
                Id = level.Id,
                NameLocId = level.NameLocId,
                DescLocId = level.DescLocId,
                UIPosition = level.UIPosition,
                Icon = level.Icon,
                Stable = level.Stable,
                Exits = level.Exits,
                PlayerCount = totalPlayers,
                Instances = instances,
            });
        }

        OverviewControl.UpdateState(levels, state.CurrentLevelId);
    }
}
