using System.Numerics;
using Content.Client._CE.UserInterface.Systems.NodeTree;
using Content.Shared._CE.Procedural.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.Procedural.Admin;

[GenerateTypedNameReferences]
public sealed partial class CEAdminDungeonOverviewWindow : DefaultWindow
{
    /// <summary>
    /// One <c>uiPosition</c> unit in the prototype equals half a rendered sprite,
    /// so two units = one full cell (a 1-cell horizontal/vertical shift does not overlap
    /// the neighbouring node). The demiplane_map.rsi sprites are 48px and drawn at 1.5x,
    /// giving 72px per cell and 36px per unit at local UI scale 1.
    /// </summary>
    private const float PositionUnit = 36f;

    private static readonly ResPath NodeTreeRsi = new("/Textures/_CE/Interface/NodeTree/demiplane_map.rsi");

    public event Action<NetEntity>? OnTeleportRequested;

    private CEAdminDungeonOverviewState? _state;
    private string? _selectedLevelId;

    public CEAdminDungeonOverviewWindow()
    {
        RobustXamlLoader.Load(this);

        GraphControl.OnNodeSelected += OnNodeSelected;
        GraphControl.OnOffsetChanged += offset =>
        {
            // Scroll the parallax background slightly in the opposite direction while
            // the user pans the graph — matches the behaviour of the skill tree window.
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000);
        };

        ClearSelection();
    }

    public void UpdateState(CEAdminDungeonOverviewState state)
    {
        _state = state;

        var nodes = new HashSet<CENodeTreeElement>();
        var edges = new HashSet<(string, string)>();

        var defaultIcon = new SpriteSpecifier.Rsi(NodeTreeRsi, "center");

        foreach (var level in state.Levels)
        {
            var playerCount = 0;
            foreach (var inst in level.Instances)
                playerCount += inst.Players.Count;

            var isCurrent = state.CurrentLevelId == level.Id;

            var node = new CENodeTreeElement(
                nodeKey: level.Id,
                gained: playerCount > 0,
                active: isCurrent,
                uiPosition: new Vector2(level.UIPosition.X, level.UIPosition.Y) * PositionUnit,
                icon: level.Icon ?? defaultIcon,
                label: playerCount > 0 ? playerCount.ToString() : null);

            nodes.Add(node);

            foreach (var target in level.Exits)
                edges.Add((level.Id, target));
        }

        var uiState = new CENodeTreeUiState(
            nodes,
            edges,
            frameIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "frame"),
            hoveredIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "hovered"),
            selectedIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "selected"),
            learnedIcon: new SpriteSpecifier.Rsi(NodeTreeRsi, "learned"))
        {
            DirectedEdges = true,
        };
        GraphControl.UpdateState(uiState);

        // Preserve selection if possible.
        if (_selectedLevelId != null && state.Levels.Exists(l => l.Id == _selectedLevelId))
            ShowLevelDetails(_selectedLevelId);
        else
            ClearSelection();
    }

    private void OnNodeSelected(CENodeTreeElement? node)
    {
        if (node == null)
        {
            ClearSelection();
            return;
        }

        _selectedLevelId = node.NodeKey;
        ShowLevelDetails(node.NodeKey);
    }

    private void ClearSelection()
    {
        _selectedLevelId = null;
        LevelName.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("ce-admin-dungeon-overview-no-selection")));
        LevelDesc.SetMessage(FormattedMessage.FromMarkupPermissive(string.Empty));
        InstancesContainer.RemoveAllChildren();
    }

    private void ShowLevelDetails(string levelId)
    {
        if (_state == null)
            return;

        CEAdminDungeonOverviewLevelEntry? level = null;
        foreach (var l in _state.Levels)
        {
            if (l.Id == levelId)
            {
                level = l;
                break;
            }
        }

        if (level == null)
        {
            ClearSelection();
            return;
        }

        var nameText = !string.IsNullOrEmpty(level.NameLocId)
            ? Loc.GetString(level.NameLocId)
            : level.Id;
        LevelName.SetMessage(FormattedMessage.FromMarkupPermissive($"[head=2]{nameText}[/head]"));

        LevelDesc.SetMessage(FormattedMessage.FromMarkupPermissive(
            !string.IsNullOrEmpty(level.DescLocId)
                ? Loc.GetString(level.DescLocId)
                : string.Empty));

        InstancesContainer.RemoveAllChildren();

        if (level.Instances.Count == 0)
        {
            InstancesContainer.AddChild(new Label
            {
                Text = Loc.GetString("ce-admin-dungeon-overview-no-instances"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        var idx = 1;
        foreach (var inst in level.Instances)
        {
            var instHeader = new Label
            {
                Text = Loc.GetString("ce-admin-dungeon-overview-instance-header",
                    ("index", idx++),
                    ("players", inst.Players.Count)),
                StyleClasses = { "LabelKeyText" },
                Margin = new Thickness(0, 5, 0, 2),
            };
            InstancesContainer.AddChild(instHeader);

            if (inst.Players.Count == 0)
            {
                InstancesContainer.AddChild(new Label
                {
                    Text = Loc.GetString("ce-admin-dungeon-overview-instance-empty"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(10, 0, 0, 0),
                });
                continue;
            }

            foreach (var player in inst.Players)
            {
                var button = new Button
                {
                    Text = Loc.GetString("ce-admin-dungeon-overview-player-entry",
                        ("character", string.IsNullOrWhiteSpace(player.CharacterName) ? "?" : player.CharacterName),
                        ("account", string.IsNullOrWhiteSpace(player.AccountName) ? "?" : player.AccountName)),
                    StyleClasses = { "OpenBoth" },
                    Margin = new Thickness(10, 0, 0, 2),
                    HorizontalExpand = true,
                };

                var target = player.Entity;
                button.OnPressed += _ => OnTeleportRequested?.Invoke(target);
                InstancesContainer.AddChild(button);
            }
        }
    }
}
