using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class CEAchievementEntry : PanelContainer
{
    public CEAchievementEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetData(string displayName, string displayDescription, bool isEarned, float percentage, bool showAdminId, string id)
    {
        NameLabel.SetMessage(displayName + (showAdminId ? $" [{id}]" : ""), isEarned ? Color.White : Color.LightGray);
        DescLabel.SetMessage(displayDescription, isEarned ? Color.White : Color.LightGray);
        PercentLabel.Text = Loc.GetString("ce-achievements-percentage", ("percent", percentage.ToString("F1")));
        PercentLabel.FontColorOverride = Color.LightGray;

        // Fill bar colour: green for earned, bluish for unearned (matches previous behaviour)
        FillBar.FillPercent = percentage;
        FillBar.FillColor = isEarned
            ? new Color(0.2f, 0.6f, 0.2f, 0.35f)
            : new Color(0.3f, 0.3f, 0.5f, 0.3f);

        // Modulate the entry panel: keep earned green, unearned darker blueish tint
        Modulate = isEarned ? new Color(0.7f, 1f, 0.7f) : Color.White;
    }
}
