using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Achievements.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using StyleClass = Content.Client.Stylesheets.StyleClass;

namespace Content.Client._CE.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class CEAchievementsWindow : FancyWindow
{
    [Dependency] private readonly CEAchievementsManager _achievementsManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    public CEAchievementsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void Opened()
    {
        base.Opened();

        PopulateAchievements();
        _achievementsManager.AchievementsUpdated += PopulateAchievements;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _achievementsManager.AchievementsUpdated -= PopulateAchievements;
    }

    private void PopulateAchievements()
    {
        AchievementsList.RemoveAllChildren();

        if (!_achievementsManager.DataLoaded)
        {
            var loadingLabel = new Label
            {
                Text = Loc.GetString("ce-achievements-loading"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0),
            };

            AchievementsList.AddChild(loadingLabel);
            return;
        }

        var allAchievements = _protoManager.EnumeratePrototypes<CEAchievementPrototype>().ToList();
        var playerAchievements = _achievementsManager.PlayerAchievements;
        var percentages = _achievementsManager.AchievementPercentages;

        // Split into earned and unearned
        var earned = allAchievements
            .Where(a => playerAchievements.Contains(a.ID))
            .ToList();

        var unearned = allAchievements
            .Where(a => !playerAchievements.Contains(a.ID))
            .ToList();

        // Sort both lists by popularity (highest percentage first)
        earned.Sort((a, b) =>
        {
            var pA = percentages.GetValueOrDefault(a.ID, 0f);
            var pB = percentages.GetValueOrDefault(b.ID, 0f);
            return pB.CompareTo(pA);
        });

        unearned.Sort((a, b) =>
        {
            var pA = percentages.GetValueOrDefault(a.ID, 0f);
            var pB = percentages.GetValueOrDefault(b.ID, 0f);
            return pB.CompareTo(pA);
        });

        // Add earned achievements header if any
        if (earned.Count > 0)
        {
            var earnedHeader = new Label
            {
                Text = Loc.GetString("ce-achievements-earned-header"),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 4, 4, 2),
            };
            earnedHeader.AddStyleClass(StyleClass.LabelHeading);
            AchievementsList.AddChild(earnedHeader);

            foreach (var achievement in earned)
            {
                var percent = percentages.GetValueOrDefault(achievement.ID, 0f);
                AchievementsList.AddChild(CreateEntry(achievement, true, percent));
            }
        }

        // Add unearned achievements header
        if (unearned.Count > 0)
        {
            var unearnedHeader = new Label
            {
                Text = Loc.GetString("ce-achievements-locked-header"),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 12, 4, 2),
            };
            unearnedHeader.AddStyleClass(StyleClass.LabelHeading);
            AchievementsList.AddChild(unearnedHeader);

            foreach (var achievement in unearned)
            {
                var percent = percentages.GetValueOrDefault(achievement.ID, 0f);
                AchievementsList.AddChild(CreateEntry(achievement, false, percent));
            }
        }

        if (earned.Count == 0 && unearned.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("ce-achievements-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0),
            };

            AchievementsList.AddChild(emptyLabel);
        }
    }

    private static PanelContainer CreateEntry(
        CEAchievementPrototype achievement,
        bool isEarned,
        float percentage)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(2),
        };
        panel.AddStyleClass("BackgroundPanel");

        if (isEarned)
            panel.Modulate = new Color(0.7f, 1f, 0.7f, 1f);
        else
            panel.Modulate = new Color(0.6f, 0.6f, 0.6f, 1f);

        // Fill bar background showing the percentage of players who have this achievement.
        // PanelContainer overlays children, so this is drawn behind the content.
        var fillBar = new CEAchievementFillBar
        {
            FillPercent = percentage,
            FillColor = isEarned
                ? new Color(0.2f, 0.6f, 0.2f, 0.35f)
                : new Color(0.3f, 0.3f, 0.5f, 0.3f),
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        panel.AddChild(fillBar);

        var hBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(8, 6, 8, 6),
        };

        // Checkmark or lock indicator
        var statusLabel = new Label
        {
            Text = isEarned ? "✓" : "✗",
            MinWidth = 24,
            VerticalAlignment = VAlignment.Top,
        };

        if (isEarned)
            statusLabel.FontColorOverride = Color.Green;
        else
            statusLabel.FontColorOverride = Color.Gray;

        hBox.AddChild(statusLabel);

        // Name and description
        var infoBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var nameLabel = new Label
        {
            Text = Loc.GetString(achievement.Name),
        };
        nameLabel.AddStyleClass(StyleClass.LabelSubText);
        nameLabel.FontColorOverride = isEarned ? Color.White : Color.LightGray;
        infoBox.AddChild(nameLabel);

        var desc = Loc.GetString(achievement.Description);
        if (!string.IsNullOrEmpty(desc))
        {
            var descLabel = new RichTextLabel
            {
                Margin = new Thickness(0, 2, 0, 0),
            };
            descLabel.SetMessage(desc);
            infoBox.AddChild(descLabel);
        }

        hBox.AddChild(infoBox);

        // Percentage label
        var percentLabel = new Label
        {
            Text = Loc.GetString("ce-achievements-percentage",
                ("percent", percentage.ToString("F1"))),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Right,
            MinWidth = 60,
        };
        percentLabel.FontColorOverride = Color.LightGray;
        hBox.AddChild(percentLabel);

        panel.AddChild(hBox);

        return panel;
    }
}
