using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Achievements.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using StyleClass = Content.Client.Stylesheets.StyleClass;

namespace Content.Client._CE.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class CEAchievementsWindow : FancyWindow
{
    [Dependency] private readonly CEAchievementsManager _achievementsManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IClientAdminManager _adminManager = default!;
    private readonly SpriteSystem _sprite = default!;

    public CEAchievementsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
    }

    protected override void Opened()
    {
        base.Opened();

        PopulateAchievements();
        _achievementsManager.AchievementsUpdated += PopulateAchievements;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _achievementsManager.AchievementsUpdated -= PopulateAchievements;
    }

    private void PopulateAchievements()
    {
        AchievementsList.RemoveAllChildren();

        if (!_achievementsManager.DataLoaded)
        {
            var loadingLabel = new Label
            {
                Text = Loc.GetString("ce-achievements-loading"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0),
            };

            AchievementsList.AddChild(loadingLabel);
            return;
        }

        var allAchievements = _protoManager.EnumeratePrototypes<CEAchievementPrototype>().ToList();
        var playerAchievements = _achievementsManager.PlayerAchievements;
        var percentages = _achievementsManager.AchievementPercentages;

        // Split into earned and unearned
        var earned = allAchievements
            .Where(a => playerAchievements.Contains(a.ID))
            .ToList();

        var unearned = allAchievements
            .Where(a => !playerAchievements.Contains(a.ID))
            .ToList();

        // Sort both lists by popularity (highest percentage first)
        earned.Sort((a, b) =>
        {
            var pA = percentages.GetValueOrDefault(a.ID, 0f);
            var pB = percentages.GetValueOrDefault(b.ID, 0f);
            return pB.CompareTo(pA);
        });

        unearned.Sort((a, b) =>
        {
            var pA = percentages.GetValueOrDefault(a.ID, 0f);
            var pB = percentages.GetValueOrDefault(b.ID, 0f);
            return pB.CompareTo(pA);
        });

        // Add earned achievements header if any
        if (earned.Count > 0)
        {
            var earnedHeader = new Label
            {
                Text = Loc.GetString("ce-achievements-earned-header"),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 4, 4, 2),
            };
            earnedHeader.AddStyleClass(StyleClass.LabelHeading);
            AchievementsList.AddChild(earnedHeader);

            foreach (var achievement in earned)
            {
                var percent = percentages.GetValueOrDefault(achievement.ID, 0f);
                AchievementsList.AddChild(CreateEntry(achievement, true, percent));
            }
        }

        // Add unearned achievements header
        if (unearned.Count > 0)
        {
            var unearnedHeader = new Label
            {
                Text = Loc.GetString("ce-achievements-locked-header"),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(4, 12, 4, 2),
            };
            unearnedHeader.AddStyleClass(StyleClass.LabelHeading);
            AchievementsList.AddChild(unearnedHeader);

            foreach (var achievement in unearned)
            {
                var percent = percentages.GetValueOrDefault(achievement.ID, 0f);
                AchievementsList.AddChild(CreateEntry(achievement, false, percent));
            }
        }

        if (earned.Count == 0 && unearned.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("ce-achievements-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0),
            };

            AchievementsList.AddChild(emptyLabel);
        }
    }

    private PanelContainer CreateEntry(
        CEAchievementPrototype achievement,
        bool isEarned,
        float percentage)
    {
        var entry = new CEAchievementEntry();

        // Determine display strings and icon spec
        string displayName;
        string displayDescription;
        SpriteSpecifier iconSpec;

        if (achievement.Secret && !isEarned)
        {
            displayName = "???";
            displayDescription = Loc.GetString("ce-achievements-secret");
            iconSpec = achievement.SecretIcon;
        }
        else
        {
            displayName = Loc.GetString(achievement.Name);
            displayDescription = Loc.GetString(achievement.Desc);
            iconSpec = isEarned ? achievement.UnlockedIcon : achievement.LockedIcon;
        }

        // Set icon texture using SpriteSystem
        entry.Icon.Texture = _sprite.Frame0(iconSpec);

        // Fill rest of data
        entry.SetData(displayName, displayDescription, isEarned, percentage, _adminManager.IsActive(), achievement.ID);

        return entry;
    }
}
