- type: tile
  editorHidden: false
  id: CEStonebricks
  name: ce-tiles-stonebricks
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true


- type: tile
  editorHidden: false
  id: CEStonebricksSnowed
  name: ce-tiles-stonebricks
  sprite: /Textures/_CE/Tiles/Stonebricks/snowstonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStonebricksSmallCarved1
  name: ce-tiles-stonebricks-small-carved1
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_small_carved_1.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStonebricksSmallCarved2
  name: ce-tiles-stonebricks-small-carved2
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_small_carved_2.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneLongBricks
  name: ce-tiles-stonebricks-long-bricks
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_long.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneMediumBricks
  name: ce-tiles-stonebricks-medium
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_medium.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneDiamond
  name: ce-tiles-stonebricks-diamond
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_diamond.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneSquarePattern
  name: ce-tiles-stonebricks-square-pattern
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_square_pattern.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneMediumCircles
  name: ce-tiles-stonebricks-medium-circles
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_medium_circles.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStoneSmallCircles
  name: ce-tiles-stonebricks-small-circles
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_small_circles.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEStonebricksSquareCarved
  name: ce-tiles-stonebricks-square-carved
  sprite: /Textures/_CE/Tiles/Stonebricks/stonebricks_square_carved.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE/Tiles/Stonebricks/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/stonebricks.rsi
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEDirtSeedbed
  name: ce-tiles-dirt-seedbed
  sprite: /Textures/_CE/Tiles/DirtSeedBag/seedbed.png
  variants: 2
  placementVariants:
  - 1.0
  - 1.0
  edgeSpritePriority: 100
  edgeSprites:
    SouthEast: /Textures/_CE/Tiles/DirtSeedBag/single_edge_SE.png
    NorthEast: /Textures/_CE/Tiles/DirtSeedBag/single_edge_NE.png
    NorthWest: /Textures/_CE/Tiles/DirtSeedBag/single_edge_NW.png
    SouthWest: /Textures/_CE/Tiles/DirtSeedBag/single_edge_SW.png
    South: /Textures/_CE/Tiles/DirtSeedBag/double_edge_S.png
    East: /Textures/_CE/Tiles/DirtSeedBag/double_edge_E.png
    North: /Textures/_CE/Tiles/DirtSeedBag/double_edge_N.png
    West: /Textures/_CE/Tiles/DirtSeedBag/double_edge_W.png
  iconSmoothSprite: /Textures/_CE/Tiles/Edges/dirt.rsi
  baseTurf: CEDirt
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CEGlass
  name: ce-tiles-glass
  sprite: /Textures/_CE/Tiles/glass.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: Space
  isSubfloor: true
  footstepSounds:
    collection: FootstepTile
  heatCapacity: 10000
  transparent: true
  weather: true

- type: tile
  editorHidden: false
  id: CERoofRed
  name: ce-tiles-roof
  sprite: /Textures/_CE/Tiles/roof_red.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

- type: tile
  editorHidden: false
  id: CERoofGreen
  name: ce-tiles-roof
  sprite: /Textures/_CE/Tiles/roof_green.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CEPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
